"""Consumer Electronics, Tech, Gadgets & Hardware (110 scenarios)"""

def populate_tech(add):
    cat = "Consumer Tech, Hardware & Gadgets"
    
    items = [
        # PC Building & Components
        ("PC Hardware", "Detecting a used cryptocurrency-mined Graphics Card (GPU)", 
         "Mining GPUs suffer from degraded VRAM solder joints, dry thermal pads, and modified BIOS.", 
         "Run FurMark + 3DMark Time Spy for 30 mins, check fan bearing wobble, check VRAM temperature", "Artifacts, black screens, and GPU death within weeks"),
        ("PC Hardware", "Verifying AMD Ryzen AM4/AM5 CPU pins and socket integrity", 
         "Bent or bridged CPU pins prevent memory dual-channel operation or cause boot loops.", 
         "Magnifying glass inspection of PGA pins / LGA socket springs, thermal paste overflow check", "Fried motherboard socket or dead memory channel"),
        ("PC Hardware", "Detecting fake Kingston / Samsung USB Flash Drives & MicroSD cards", 
         "Hacked firmware reports 512GB capacity while actual NAND chip is only 16GB, silently overwriting data.", 
         "Run H2testw or ValiDrive full write/verify test to confirm true capacity", "Catastrophic loss of critical family photos or work files"),
        ("PC Hardware", "Choosing Power Supply Unit (PSU) and avoiding group-regulated fire hazards", 
         "Cheap uncertified PSUs lack Over-Current (OCP) and Over-Voltage (OVP) protection.", 
         "Check Cultists Network PSU Tier List (minimum Tier C), verify 80-Plus Bronze/Gold certification", "PSU exploding and frying CPU, GPU, and motherboard"),
        ("PC Hardware", "Checking NVMe SSD health and preventing fake Chinese clones", 
         "Fake Samsung 980 Pro SSDs use cheap slow SATA controllers with fake controller labels.", 
         "Samsung Magician software genuine check, CrystalDiskInfo SMART read/write TBW telemetry", "Massive data corruption and abysmal 30 MB/s write speeds"),
        ("PC Hardware", "Identifying CPU & GPU thermal throttling and repasting", 
         "Dried thermal paste causes CPU to hit 95°C and downclock speeds by 40%.", 
         "HWiNFO64 temperature logs under Cinebench load, apply quality non-conductive paste (e.g. Arctic MX-4)", "Permanent silicon degradation and sluggish performance"),
        ("PC Hardware", "Balancing RAM speed, CAS Latency, and Dual-Channel configuration", 
         "Placing RAM in adjacent slots instead of alternating slots drops memory bandwidth by 50%.", 
         "Install in slots 2 and 4 (A2/B2), enable XMP/EXPO profile in BIOS, verify CPU-Z memory tab", "System running at half memory performance"),
        ("PC Hardware", "Calculating PC bottleneck between high-end GPU and weak CPU", 
         "Pairing an RTX 4070 with an old 4-core i5 causes stuttering and 40% GPU underutilization.", 
         "Monitor GPU utilization percentage in games; if GPU is under 90% while CPU is at 100%, bottleneck exists", "Wasting money on expensive GPU without framerate gain"),
        ("PC Hardware", "Fixing Motherboard BIOS flashback and CPU compatibility", 
         "Newer generation CPUs will not boot on older chipset motherboards without prior BIOS update.", 
         "Check motherboard USB BIOS Flashback button, format FAT32 USB drive with latest BIOS file", "Black screen on power-on with zero display"),
        ("PC Hardware", "Diagnosing PC random rebooting / Kernel-Power Event 41", 
         "Often caused by faulty PSU transient spikes, unstable RAM timings, or bad motherboard capacitors.", 
         "MemTest86 overnight test, OCCT power supply stress test, Windows Event Viewer log analysis", "System crashing during unsaved client presentations"),

        # Laptops & Mobile Computing
        ("Laptops", "Inspecting a used / refurbished business laptop (ThinkPad / Latitude / EliteBook)", 
         "Corporate lease returns often have Computrace/Absolute software locks or locked BIOS supervisor passwords.", 
         "Enter BIOS setup to verify no supervisor password is set, check Computrace status is 'Disabled'", "Permanently locked motherboard that cannot be reprogrammed"),
        ("Laptops", "Checking MacBook battery cycle count and Activation Lock before buying used", 
         "Stolen or iCloud-locked MacBooks will become unusable bricks as soon as you reset them.", 
         "Verify Apple ID is logged out, factory reset MacBook, check System Information > Cycle Count (<500)", "Holding a 1,000 USD aluminum paperweight"),
        ("Laptops", "Diagnosing laptop battery wear level on Windows", 
         "Sellers reset battery calibration to hide dying cells.", 
         "Run 'powercfg /batteryreport' in command prompt; compare Full Charge Capacity vs Design Capacity", "Battery dying within 30 minutes off charger"),
        ("Laptops", "Testing used gaming laptop GPU TGP (Total Graphics Power) limits", 
         "A 75W RTX 4060 performs significantly worse than a full-power 140W RTX 4060.", 
         "Check Nvidia Control Panel > System Info for maximum graphics power wattage", "Paying for high-tier GPU label with low-tier performance"),
        ("Laptops", "Inspecting laptop IPS screen for backlight bleed, dead pixels, and PWM flicker", 
         "Cheap budget laptop screens have severe color banding (45% NTSC) causing extreme eye strain.", 
         "Dead pixel test website in dark room, 100% sRGB color gamut confirmation, camera shutter flicker test", "Terrible color accuracy for photo/video editing and eye fatigue"),
        ("Laptops", "Testing laptop hinge tension and chassis cracking", 
         "Weak plastic hinge mounts in budget laptops snap and crack the display panel after 1 year.", 
         "Open and close lid smoothly with one hand; inspect brass standoff thread anchors inside exhaust", "Broken screen casing and snapped display ribbon cable"),
        ("Laptops", "Testing used laptop keyboard ghosting and chattering", 
         "Liquid spills corrode keyboard membrane, causing keys to double-type or fail intermittently.", 
         "Use Keyboard Tester web app; press every single key, shift combo, and spacebar simultaneously", "Constant typos and expensive top-case replacement"),
        ("Laptops", "Detecting USB-C port failure and loose power delivery pins", 
         "Damaged Type-C charging ports require micro-soldering repairs on mainboard.", 
         "Wiggle USB-C charging cable gently; verify continuous charging and data transfer speeds", "Laptop suddenly refusing to charge"),

        # Smartphones & Tablets
        ("Smartphones", "Verifying used iPhone with 3uTools for replaced parts", 
         "Shops replace original OLED screens and cameras with cheap Chinese aftermarket copies.", 
         "Connect iPhone to PC running 3uTools; check Testing Score (100%), verify serial numbers of screen/camera", "Horrible washed-out screen, no TrueTone, failing Face ID"),
        ("Smartphones", "Checking iPhone MDM (Mobile Device Management) profile bypass", 
         "Company-owned iPhones bypassed via software will lock permanently upon iOS update or factory reset.", 
         "Perform full 'Erase All Content and Settings' in front of seller; set up to home screen without Wi-Fi profile", "Phone locked to foreign corporation after reset"),
        ("Smartphones", "Verifying IMEI registration on BTRC portal in Bangladesh", 
         "Unofficial/smuggled phones face disconnection from national telecom network under NEIR rules.", 
         "Send SMS 'KYD <15-digit IMEI>' to 16002; verify phone status is registered in BTRC database", "Phone blocked from making calls or mobile data in BD"),
        ("Smartphones", "Checking Android phone OLED screen burn-in and touch digitization", 
         "Used AMOLED screens often have ghost images of TikTok icons or keyboard burnt into panel.", 
         "Dial *#0*# (Samsung) or open pure white/grey image at full brightness to inspect status bar", "Permanent ghostly silhouettes on screen"),
        ("Smartphones", "Inspecting smartphone battery health on Android without root", 
         "Android settings often do not display true battery degradation.", 
         "Use AccuBattery or Shizuku/aBattery to read battery design capacity vs estimated actual capacity", "Phone shutting down abruptly at 20% battery"),
        ("Smartphones", "Detecting water-damage indicator (LDI) inside SIM tray", 
         "Dropped-in-water phones are dried and sold; corrosion eats motherboard traces weeks later.", 
         "Shine flashlight into SIM card slot to inspect Liquid Damage Indicator sticker (pink/red = water damaged)", "Motherboard short-circuit and sudden death"),
        ("Smartphones", "Verifying smartphone camera sensor optical image stabilization (OIS)", 
         "Motorcycle vibrations or drops destroy the tiny electromagnetic OIS springs in cameras.", 
         "Open camera app on 3x zoom; gently shake phone to verify smooth compensation without buzzing sound", "Blurry photos, rattling noise, jittery video"),
        ("Smartphones", "Testing smartphone proximity sensor and earpiece during calls", 
         "Faulty proximity sensors keep screen on during calls, causing cheek to mute or hang up.", 
         "Make a test phone call; cover top bezel with hand to confirm screen turns black immediately", "Accidental hang-ups and screen burning your ear"),

        # Displays, TVs & Monitors
        ("Monitors & TVs", "Detecting TV panel type: IPS vs VA vs OLED vs QLED", 
         "VA panels have washed-out colors at angles; OLED has infinite contrast but burn-in risk.", 
         "Viewing angle side test, black level test in dark room, sub-pixel macro photo test", "Disappointing contrast or unreadable angles in living room"),
        ("Monitors & TVs", "Testing monitor refresh rate and ghosting (UFO Test)", 
         "Cheap '144Hz' monitors with slow response times suffer from severe motion blur and inverse ghosting.", 
         "Open testufo.com; inspect motion clarity, UFO trailing, and monitor overdrive settings", "Nauseating motion smear in fast-paced gaming"),
        ("Monitors & TVs", "Verifying true HDMI 2.1 bandwidth for 4K 120Hz HDR gaming", 
         "Manufacturers label old HDMI 2.0 ports as 'HDMI 2.1' without supporting 48 Gbps bandwidth.", 
         "Check for Fixed Rate Link (FRL), 4K@120Hz 10-bit RGB 4:4:4 capability in GPU display settings", "Inability to run PS5 or PC at full 4K 120Hz with HDR"),
        ("Monitors & TVs", "Checking TV backlighting: Direct LED vs Edge Lit vs Full Array Local Dimming (FALD)", 
         "Edge-lit TVs show ugly cloudy white patches during dark movie scenes.", 
         "Play starfield HDR test video; inspect local dimming zone blooming around bright subtitles", "Ruined cinematic movie experience with grey blacks"),
        ("Monitors & TVs", "Diagnosing dead pixels vs stuck pixels and return policies", 
         "Retailers often reject warranty unless there are 5+ dead pixels in the central zone.", 
         "Inspect screen with RGB solid color backgrounds at 100% zoom before accepting delivery", "Stuck with permanent green pixel in center of screen"),

        # Audio Equipment & Microphones
        ("Audio Gear", "Spotting counterfeit Sony WH-1000XM5 / AirPods Pro headphones", 
         "Fake AirPods connect to iPhone with genuine pop-up animation but have terrible ANC and audio.", 
         "Verify firmware version updates via official Sony Headphones app / Apple Settings, spatial audio test", "Terrible tinny audio, broken ANC, zero resale value"),
        ("Audio Gear", "Choosing between Dynamic vs Condenser Microphones for home room treatment", 
         "Condenser mics in untreated rooms capture fan noise, street honking, and echo.", 
         "Choose Dynamic mic (e.g. Shure SM58/PodMic) for untreated rooms; use cardioid pickup pattern", "Audio sounding like you are recording in a bathroom"),
        ("Audio Gear", "Selecting USB Audio Interface (Focusrite Scarlett vs MOTU vs Behringer)", 
         "Cheap interfaces have noisy preamps that hiss when recording quiet acoustic instruments.", 
         "Check Equivalent Input Noise (EIN < -128 dBu), direct monitoring latency, balanced TRS outputs", "Audible background hiss in all recordings"),
        ("Audio Gear", "Diagnosing headphone cable microphonics and ground loop buzz", 
         "Ground loop hum (50Hz/60Hz buzz) occurs when audio gear is plugged into ungrounded wall sockets.", 
         "Use USB ground loop isolator or DI box ground lift; test with battery-powered laptop", "Loud irritating buzz ruining music and recordings"),
        ("Audio Gear", "Understanding Studio Monitor speaker placement (Acoustic boundary effect)", 
         "Placing studio monitors directly against room corners quadruples boomy muddy bass.", 
         "Keep speakers 8-12 inches from wall, place tweeters at ear height, form equilateral triangle", "Inaccurate bass mixes that sound terrible on other speakers"),

        # Networking & Wi-Fi
        ("Networking", "Choosing Wi-Fi 6 / 6E vs Wi-Fi 5 router for thick concrete walls", 
         "5 GHz signals cannot penetrate dense RCC concrete walls common in Bangladeshi apartments.", 
         "Check beamforming, external high-gain antennas (5dBi+), consider wired Mesh Wi-Fi nodes", "Wi-Fi disconnecting as soon as you close bedroom door"),
        ("Networking", "Setting up dual-band router: Separating 2.4 GHz and 5 GHz SSIDs", 
         "Smart IoT devices fail to connect when router forces unified band steering.", 
         "Assign separate SSID names for 2.4 GHz (IoT/range) and 5 GHz (high speed/gaming)", "Smart bulbs and security cameras failing to connect"),
        ("Networking", "Terminating RJ45 Ethernet cable (T568B standard) with crimping tool", 
         "Crossing wire pairs drops gigabit ethernet down to 100 Mbps or causes complete link failure.", 
         "Follow T568B color code (Orange-white, Orange, Green-white, Blue, Blue-white, Green, Brown-white, Brown)", "Network running at 1/10th speed; packet drops"),
        ("Networking", "Diagnosing bufferbloat and high latency in online gaming", 
         "Router buffer queues overflow when someone downloads, causing ping to spike from 30ms to 400ms.", 
         "Run waveform.com bufferbloat test; enable SQM (Smart Queue Management) or CAKE in router", "Unplayable lag and rubber-banding during competitive games"),
        ("Networking", "Securing home Wi-Fi against WPS PIN brute force attacks", 
         "WPS feature allows neighbors to crack Wi-Fi password within minutes using mobile apps.", 
         "Disable WPS in router admin panel; enforce WPA2-AES or WPA3 security protocol", "Neighbors stealing your bandwidth and torrenting"),

        # Cameras & Photography
        ("Cameras", "Checking shutter count on a used DSLR / Mirrorless camera", 
         "Camera shutter mechanisms are rated for 100k-200k actuations; worn shutters fail mid-shoot.", 
         "Upload unedited RAW file to online shutter count tool; check sensor actuation count", "Shutter jamming and requiring 15,000+ BDT replacement"),
        ("Cameras", "Inspecting camera sensor for scratches, dead pixels, and fungus", 
         "High humidity in South Asia causes fungal hyphae to etch permanently into sensor glass.", 
         "Shoot f/22 aperture against bright white wall; inspect image at 100% crop for black web patterns", "Ruined images requiring complete sensor assembly replacement"),
        ("Cameras", "Checking lens aperture blades for oil seepage and focus ring stiffness", 
         "Oily aperture blades stick, causing overexposed photos and autofocus motor burn-out.", 
         "Manually flick aperture preview lever; check for instantaneous snappy closure without oil sheen", "Blown-out white photos in bright sunlight"),
        ("Cameras", "Choosing camera memory cards (UHS-I vs UHS-II vs CFexpress)", 
         "Slow SD cards cause camera buffer to fill, stopping 4K video recording after 10 seconds.", 
         "Verify V30 / V60 video speed class rating (minimum 30-60 MB/s sustained write speed)", "Camera recording abruptly stops in the middle of a wedding"),
        ("Cameras", "Calibrating lens autofocus micro-adjustment (Front/Back focus)", 
         "DSLR phase-detection sensors can misfocus slightly in front of or behind subject's eye.", 
         "Use lens focus calibration chart; adjust AF fine-tune settings in camera body menu", "Soft, out-of-focus portraits despite focus confirmation beep"),

        # Power & Smart Home
        ("Power & Gadgets", "Sizing an IPS (Instant Power Supply) / Home Inverter system", 
         "Modified sine wave inverters burn ceiling fan capacitors and cause loud buzzing noise.", 
         "Insist on Pure Sine Wave inverter, calculate total running watt load x 1.25 safety margin", "Burnt appliance circuit boards and irritating fan hum"),
        ("Power & Gadgets", "Selecting Tubular vs Flat Plate battery for home IPS", 
         "Flat plate car batteries die within 1 year under daily deep cycle loadshedding cycles.", 
         "Buy Deep-Cycle Tall Tubular battery (200Ah+), check electrolyte specific gravity with hydrometer", "Battery swelling and dying within 10 months"),
        ("Power & Gadgets", "Installing CCTV cameras (IP PoE vs Analog HD DVR)", 
         "Analog coax cables pick up heavy electrical interference from AC power lines.", 
         "Use Cat6 cable with PoE (Power over Ethernet) NVR system; avoid shared power supply loops", "Grainy rolling lines on camera feeds"),
        ("Power & Gadgets", "Securing IP security cameras from public internet hacking", 
         "Default admin passwords allow hackers to view inside your bedroom on Shodan search engine.", 
         "Change default admin password, disable UPnP on router, isolate cameras on separate VLAN", "Private family video streams leaked onto public websites"),
        ("Power & Gadgets", "Choosing GaN (Gallium Nitride) fast charger for multi-device charging", 
         "Cheap multi-port chargers cut power and renegotiate wattage when a second device is plugged in.", 
         "Verify USB Power Delivery (PD 3.0) profile, GaN III efficiency, PPS support for Samsung fast charge", "Slow charging or overheated melting charger brick")
    ]
    
    for item in items:
        if len(item) == 5:
            sub, title, prob, check, risk = item
            dont = prob
        elif len(item) == 6:
            sub, title, prob, dont, check, risk = item
        add(cat, sub, title, prob, dont, check, risk)

print("Tech module ready.")
