"""Government Identity, Civil Registry, Taxes & Bureaucracy (85 scenarios)"""

def populate_govt(add):
    cat = "Government Identity, Civil Registry & Taxes"
    
    items = [
        # E-Passport & Immigration Bureaucracy
        ("E-Passport", "Applying for a new E-Passport online without spelling mistakes", 
         "A single letter discrepancy between NID and passport application locks the file in adjudication.", 
         "epassport.gov.bd account, verify exact character match with Smart NID, payment via A-Challan", "Application stuck in 'Pending Adjudication' for months"),
        ("E-Passport", "Navigating Police Special Branch (SB) verification for passport", 
         "SB officers conduct field background checks at permanent and present addresses.", 
         "Keep utility bill, ward commissioner citizen certificate, NID copies, student/job ID ready", "Adverse police report leading to passport rejection"),
        ("E-Passport", "Correcting old handwritten/MRP passport data to match Smart NID", 
         "Ministry of Home Affairs circular allows matching passport data to NID without court affidavit.", 
         "Attach Home Ministry circular copy, Smart NID, SSC certificate if required", "Passport office counter rejection by uniformed officials"),
        ("E-Passport", "Applying for emergency urgent / express passport issuance", 
         "Paying express fee does not bypass police verification unless previously verified.", 
         "Medical emergency recommendation, foreign university admission letter, express bank challan", "Paying double fees without receiving passport on time"),
        ("E-Passport", "Renewing expired passport with pending criminal case or bail", 
         "Pending criminal charges trigger automated passport hold under Passport Act.", 
         "Obtain certified court order / bail bond from trial court granting permission to travel", "Passport confiscated and detention at regional passport office"),
        ("E-Passport", "Adding spouse name or marital status change in passport", 
         "Requires certified Muslim Marriage Registry Kabin-nama or legal marriage certificate.", 
         "Registered Kabin-nama, spouse NID copy, joint declaration affidavit", "Application rejected or marriage status left unendorsed"),
        ("E-Passport", "Applying for child/minor E-Passport (under 18 years)", 
         "Minors under 18 receive only 5-year validity passports and require 17-digit online birth certificate.", 
         "17-digit BDRIS birth certificate, parents' Smart NIDs, 3R size biometric photo", "Application rejected due to manual handwritten birth slip"),
        ("E-Passport", "Handling passport lost while travelling domestically", 
         "Cannot get a reissue without formal Police GD mentioning exact lost passport number.", 
         "File GD at local Thana, obtain certified Thana seal, apply under 'Lost' category", "Accused of holding dual fraudulent passports"),
        ("E-Passport", "Changing signature in E-Passport during renewal", 
         "Drastic signature changes require special affidavit and counter-verification.", 
         "Executive Magistrate / Notary Public affidavit explaining signature change, updated NID", "Biometric enrollment machine rejection"),
        ("E-Passport", "Tracking passport stuck in 'Pending Police Verification' or 'Pending at SB'", 
         "Files often sit on local SB sub-inspector's desk for weeks awaiting speed money.", 
         "Track online; contact District SB office / DSB superintendent with tracking slip", "Missing crucial travel or visa deadline"),

        # Smart NID (National Identity Card)
        ("Smart NID", "Registering as a new voter and obtaining first Smart NID", 
         "Citizens over 18 must submit primary birth and educational proof to Upazila Election Office.", 
         "17-digit online birth certificate, SSC certificate, parents' NID, utility bill proof", "Registration delayed or voter area mapped incorrectly"),
        ("Smart NID", "Correcting Date of Birth (DOB) in Smart NID card", 
         "Election Commission classifies DOB correction as 'Category C' requiring strict primary proof.", 
         "SSC certificate (mandatory if educated), online birth registration, DG approval file", "Rejection by Election Commission scrutiny committee"),
        ("Smart NID", "Correcting parents' names or spelling in NID", 
         "Requires parents' Smart NIDs or death certificates plus siblings' NIDs for consistency.", 
         "Parents' NIDs, inheritance Waris certificate, sibling NIDs, online correction form", "Application rejected for family lineage inconsistency"),
        ("Smart NID", "Transferring voter area / constituency from village to city", 
         "Must prove physical residence in new location via house deed or tenancy agreement.", 
         "Ward councillor certificate, tenancy contract, electricity bill in applicant's name", "Cannot vote or obtain local civic certificates in new city"),
        ("Smart NID", "Re-issuing lost Smart NID card immediately", 
         "Applying online allows instant download of digital NID PDF with official QR code.", 
         "services.nidw.gov.bd account, face verification via NID Wallet app, fee challan", "Paying touts for emergency plastic printouts"),
        ("Smart NID", "Correcting educational qualification or occupation in NID database", 
         "Changing status to 'Professional' or 'Engineer/Doctor' requires certified professional degrees.", 
         "Certified degree certificate, BMDC/IEB registration card, employer appointment letter", "Online application rejected by Upazila Election Officer"),
        ("Smart NID", "Handling duplicate NID / dual voter registration problem", 
         "Registering twice is a criminal offense under Electoral Rolls Act resulting in automated freeze.", 
         "File surrender application for duplicate voter ID to Election Commission Secretariat", "Arrest warrant or permanent freeze of both NID numbers"),
        ("Smart NID", "Obtaining NID for an illiterate senior citizen without certificates", 
         "Requires age assessment by government Civil Surgeon and family lineage tree.", 
         "Civil Surgeon age verification report, Union Parishad chairman affidavit, children's NIDs", "Permanent disenfranchisement and denial of old-age allowance"),

        # Civil Registry: Birth, Marriage, Death & Succession
        ("Civil Registry", "Getting a 17-digit digital Birth Registration Certificate (BRC)", 
         "Old manual handwritten birth certificates are completely invalid for passport or school admission.", 
         "bdris.gov.bd application, parents' digital birth certificates, hospital discharge slip", "Rejection of passport or visa applications"),
        ("Civil Registry", "Translating and notarizing Birth Certificate into English", 
         "Embassy visa sections reject unverified translations with mismatched name spellings.", 
         "Official English version from City Corporation, verify spelling against passport", "Visa delay or rejection due to spelling mismatch"),
        ("Civil Registry", "Registering Muslim Marriage (Kabin-nama) with official Kazi", 
         "Unregistered marriages have no legal standing in property claims, alimony, or visa spousal files.", 
         "Authorized government Kazi register, Form 16 Kabin, specified Dower (Dain-Meher)", "Denial of spousal visa or forfeiture of maintenance rights"),
        ("Civil Registry", "Registering Hindu Marriage under Hindu Marriage Registration Act", 
         "Hindu marriage registration is optional but mandatory for foreign visa and property ownership.", 
         "Government Hindu Marriage Registrar, marriage invitation card, priest affidavit, photos", "Inability to obtain foreign spouse visa"),
        ("Civil Registry", "Executing legal divorce notice under Muslim Family Laws Ordinance (Section 7)", 
         "Divorce is legally incomplete without sending formal notice to City Corporation Mayor/Chairman.", 
         "Written registered post notice to Mayor and spouse, 90-day conciliation period, final certificate", "Divorce legally void; facing bigamy/adultery lawsuits"),
        ("Civil Registry", "Obtaining Legal Heir / Waris Certificate (ওয়ারিশান সনদ)", 
         "Local Ward Councillor / Chairman issues certificate listing all legitimate living heirs.", 
         "NID copies of all heirs, family tree diagram, two neighbor witness signatures", "Omission of daughters or minors resulting in title litigation"),
        ("Civil Registry", "Obtaining Succession Certificate from Civil Court for bank accounts", 
         "Banks freeze deceased person's accounts above threshold without Civil Court succession order.", 
         "File Succession Miscellaneous Case before District Judge Court, schedule of assets", "Funds locked in deceased parent's bank account for years"),
        ("Civil Registry", "Registering official Death Certificate and cause of death", 
         "Hospital death certificate must be digitized on BDRIS within 45 days to avoid court affidavit.", 
         "Hospital death slip, cemetery burial clearance receipt, online BDRIS entry", "Complicated court procedure to claim pension or life insurance"),
        ("Civil Registry", "Special Marriage Act registration for inter-faith or civil couples", 
         "Requires 14-day public notice before marriage registrar under Special Marriage Act 1872.", 
         "Notice to Registrar of Special Marriages, age proof (21 for male, 18 for female), 3 witnesses", "Marriage invalidated or challenged by family members"),
        ("Civil Registry", "Registering adoption or legal guardianship of a child", 
         "Under statutory law in Bangladesh, formal legal adoption is granted via Family Court guardianship.", 
         "File Guardianship suit under Guardians and Wards Act in Family Court, home study report", "Biological parents reclaiming child years later"),

        # Income Tax & NBR Compliance
        ("Income Tax", "Mandatory online e-Return submission on etaxnbr.gov.bd", 
         "Manual paper returns are phased out; missing deadline incurs interest penalty and penalty fees.", 
         "Biometric SIM linked to NID, e-TIN, salary bank certificate, investment tax rebate proofs", "Frozen bank accounts and loss of 44+ mandatory services"),
        ("Income Tax", "Submitting a 'Zero Tax Return' for unemployed, students, or housewives", 
         "Mandatory to hold credit cards, sell land, or trade licenses even with zero income.", 
         "Declare income below tax threshold (3.5 Lakh BDT), asset statement under 40 Lakh BDT", "Penalties for non-filing under Section 124 of Income Tax Act"),
        ("Income Tax", "Declaring foreign freelance income / IT export remittance", 
         "IT freelance earnings are legally tax-exempt, but failure to file form IT-10B triggers tax notices.", 
         "Bank PRC (Proceed Realization Certificate), Form 10BB schedule, client invoices", "Tax commissioner freezing account on suspicion of black money"),
        ("Income Tax", "Calculating Capital Gains Tax on land and apartment sale", 
         "Sub-registry source tax (Section 53H) must be reconciled in annual income tax return.", 
         "Registered deed value, Sub-registry tax challan copy, deduction of indexed acquisition cost", "Heavy surprise audit tax assessment notice"),
        ("Income Tax", "Claiming Tax Rebate through approved investments (DPS, Stocks, Life Insurance)", 
         "Investing in approved schemes saves up to 15% on payable income tax.", 
         "DPS deposit statements, BO account portfolio statement, life insurance premium receipts", "Paying maximum tax bracket without claiming eligible rebates"),
        ("Income Tax", "Responding to an Income Tax Audit Notice (Section 120/130)", 
         "Ignoring tax assessment notices results in ex-parte assessment with massive fabricated liabilities.", 
         "Submit written explanation with bank ledger, source of assets, appear before DCT", "Bank account attachment order and freezing of funds"),
        ("Income Tax", "Declaring gold, jewelry, and inherited wealth in asset statement", 
         "Undeclared gold or ancestral jewelry can be seized as unexplained wealth by NBR.", 
         "Form IT-10B asset schedule, disclose heirloom weight, marriage gift declaration", "Seizure and 100% penalty on undisclosed gold"),
        ("Income Tax", "Obtaining Tax Clearance Certificate for travel abroad or business tenders", 
         "Required by government contractors and foreign nationals working in Bangladesh.", 
         "Application to circle Deputy Commissioner of Taxes (DCT), clearance order", "Disqualification from government tender bidding"),

        # Business Licensing, Trade & Startups
        ("Business & Trade", "Obtaining a new Trade License from City Corporation / Union Parishad", 
         "Operating any commercial venture without trade license attracts mobile court sealing.", 
         "Commercial rent agreement, holding tax receipt, applicant NID, nature of business form", "Shop or office sealed by City Corporation mobile court"),
        ("Business & Trade", "Registering a Private Limited Company with RJSC", 
         "Name clearance, drafting Memorandum and Articles of Association (MoA/AoA) via portal.", 
         "Name clearance slip, digital signature, paid-up capital bank account, RJSC filing", "Rejection of company incorporation or trademark conflict"),
        ("Business & Trade", "Registering for VAT / Business Identification Number (BIN)", 
         "All commercial importers, wholesalers, and manufacturers must hold a 9-digit online BIN.", 
         "vat.gov.bd registration, trade license, bank certificate, factory/shop photos", "Inability to clear imports through customs or invoice clients"),
        ("Business & Trade", "Opening a commercial company bank account (Current Account)", 
         "Banks require exhaustive KYC and board resolution before activating corporate accounts.", 
         "RJSC certified MoA, Form XII, board resolution, trade license, e-TIN, signatories' NIDs", "Account opening rejected; funds stuck in personal accounts"),
        ("Business & Trade", "Registering a Trademark with Department of Patents, Designs and Trademarks (DPDT)", 
         "Operating a brand without trademark allows copycats to steal your name and logo.", 
         "Form TM-1, trademark class search, logo vector file, power of attorney to IP lawyer", "Rival registering your brand name and suing you to stop sales"),
        ("Business & Trade", "Obtaining Fire Safety License from Fire Service and Civil Defence", 
         "Required for restaurants, factories, garment units, and multi-story commercial offices.", 
         "Fire layout plan, certified fire extinguishers, evacuation map, fire drill certificate", "Immediate factory closure or massive liability during fires"),
        ("Business & Trade", "Applying for Environmental Clearance Certificate (ECC) from DoE", 
         "Industries categorized as Green, Orange, or Red cannot operate without DoE approval.", 
         "Effluent Treatment Plant (ETP) design, environmental management plan, DoE site visit", "Criminal prosecution and disconnection of electricity/gas"),
        ("Business & Trade", "Securing an Import Registration Certificate (IRC) or ERC", 
         "Cannot clear commercial goods through Chittagong Port without valid IRC/ERC.", 
         "Chamber of Commerce membership, trade license, bank solvency, CCI&E portal application", "Goods confiscated at seaport incurring daily demurrage charges"),
        ("Business & Trade", "Setting up an e-Commerce business complying with DBID guidelines", 
         "Ministry of Commerce requires Digital Business Identification (DBID) for online sellers.", 
         "DBID portal registration, physical office verification, clear return/refund policy", "Facebook page banned or payment gateway frozen by central bank")
    ]
    
    for item in items:
        if len(item) == 5:
            sub, title, prob, check, risk = item
            dont = prob
        elif len(item) == 6:
            sub, title, prob, dont, check, risk = item
        add(cat, sub, title, prob, dont, check, risk)

print("Govt module ready.")
