"""Immigration, Study Abroad, Visas & Foreign Travel (90 scenarios)"""

def populate_immigration(add):
    cat = "Immigration, Study Abroad & Foreign Travel"
    
    items = [
        # Higher Studies Abroad
        ("Higher Studies Abroad", "Securing a graduate assistantship (RA/TA) for Master's/PhD in USA", 
         "Applying without contacting professors directly results in rejection or unfunded admission.", 
         "Read recent professor papers, draft personalized research email, align CV with lab focus", "Stuck with 50,000 USD/year out-of-pocket tuition"),
        ("Higher Studies Abroad", "Opening a German Blocked Account (Sperrkonto) for student visa", 
         "Funds must be deposited in a German federal-approved provider (Expatrio/Fintiba) before visa.", 
         "Proof of 11,208+ EUR deposit, health insurance combo package, confirmation letter", "Student visa rejection at German Embassy"),
        ("Higher Studies Abroad", "Preparing WES (World Education Services) credential evaluation", 
         "University transcripts must be sent directly by the registrar in a sealed, stamped envelope.", 
         "Board/University sealed envelope procedure, WES reference number on envelope", "Documents rejected by WES; months of application delay"),
        ("Higher Studies Abroad", "Attesting educational certificates from Ministry of Education & MOFA", 
         "Foreign universities reject certificates without verified counter-attestations.", 
         "Board verification ➔ Higher Education division ➔ MOFA counter-signature online appointment", "Visa appointment cancelled due to unverified degrees"),
        ("Higher Studies Abroad", "Drafting a plagiarism-free Statement of Purpose (SOP)", 
         "Using AI or generic agency templates triggers university plagiarism detection software.", 
         "Explain academic trajectory, research gaps, why this specific university, career goals", "Instant academic blacklist and rejection"),
        ("Higher Studies Abroad", "Handling F-1 US Student Visa Interview at the Embassy", 
         "Failing to demonstrate non-immigrant intent (ties to home country) triggers 214(b) rejection.", 
         "I-20, SEVIS fee receipt, genuine family/property ties, clear articulation of post-study plan", "Permanent visa denial under Section 214(b)"),
        ("Higher Studies Abroad", "Arranging genuine bank solvency and sponsor statement", 
         "Sudden unexplainable deposits ('season money') in sponsor's account trigger fraud investigation.", 
         "6-month bank statement with clear tax returns, source of funds, affidavit of financial support", "Visa ban for submitting fraudulent financial documents"),
        ("Higher Studies Abroad", "Meeting English proficiency requirements (IELTS vs PTE vs TOEFL vs Duolingo)", 
         "Some countries or universities do not accept Duolingo or online home-edition tests.", 
         "Check specific university minimum sub-score requirements (e.g. 6.0 in each band)", "Admission rescinded after paying non-refundable deposit"),
        ("Higher Studies Abroad", "Applying for Canada Student Direct Stream (SDS) / Study Permit", 
         "GIC (Guaranteed Investment Certificate) and upfront medical exam are mandatory.", 
         "10,000+ CAD GIC certificate from Scotiabank/CIBC, upfront medical exam, IELTS 6.0+", "Study permit rejection for insufficient funds"),
        ("Higher Studies Abroad", "Applying for Australian Subclass 500 Student Visa and Genuine Student (GS) test", 
         "High risk country ratings require rigorous proof of academic progression and career ROI.", 
         "GS written statement, OSHC health cover, confirmation of enrollment (CoE)", "Visa refusal affecting all future Five Eyes visa applications"),

        # Work Visas & Overseas Employment
        ("Work Visas & Employment", "Registering on Ami Probashi app and obtaining BMET Smart Card", 
         "Leaving Bangladesh for foreign employment without BMET clearance card is illegal.", 
         "Ami Probashi biometric registration, pre-departure briefing (PDO), BMET immigration clearance", "Offloaded by immigration police at airport gate"),
        ("Work Visas & Employment", "Verifying foreign recruiting agency BAIRA license authenticity", 
         "Unlicensed touts promise European/Gulf visas and disappear with 5-10 Lakh BDT.", 
         "Ministry of Expatriates' Welfare recruiting agency database search, demand letter vetting", "Human trafficking victim or stranded without visa"),
        ("Work Visas & Employment", "Passing GAMCA (Wafid) medical test for GCC Gulf countries", 
         "Undiagnosed hepatitis B, old healed lung scars, or minor heart murmurs cause permanent 'Unfit'.", 
         "Pre-GAMCA private screening (X-ray, blood tests), official Wafid medical slip appointment", "2-year medical ban across all GCC countries"),
        ("Work Visas & Employment", "Securing a Poland / Romania / Croatia work permit and embassy appointment", 
         "Work permits (Zezwolenie) expire within months while waiting for elusive embassy slots.", 
         "Direct employer work permit verification at Voivodship office, VFS appointment tracking", "Expired work permit and lost agency advance money"),
        ("Work Visas & Employment", "Signing foreign employment contract (Bilingual Arabic/English vs Bangla)", 
         "Workers sign Arabic contracts with lower salaries and worse conditions than promised in Dhaka.", 
         "Verify attested contract from Bangladesh Embassy in destination country, salary clause", "Working for half the promised salary in sweatshop conditions"),
        ("Work Visas & Employment", "Spotting fake European work visa stickers and forged job offers", 
         "Scammers forge Schengen visa stickers with non-existent barcode data.", 
         "Verify visa issuance with destination country embassy; cross-check company tax registry", "Arrested at transit airport and deported in handcuffs"),
        ("Work Visas & Employment", "Applying for UK Skilled Worker Visa and Certificate of Sponsorship (CoS)", 
         "Unlicensed sponsors assign fake CoS allocations that Home Office revokes mid-process.", 
         "Check UK Home Office Register of Licensed Sponsors, valid CoS number, English B1 test", "Visa refusal and loss of thousands in application fees"),
        ("Work Visas & Employment", "Navigating the Kafala sponsorship transfer system in Middle East", 
         "Leaving an abusive employer without formal electronic transfer is treated as 'Huroob' (runaway).", 
         "Qiwa / Absher electronic contract transfer, labor office grievance filing", "Imprisonment and immediate deportation with lifetime ban"),
        ("Work Visas & Employment", "Recovering unpaid wages through Bangladesh Embassy Labor Wing abroad", 
         "Foreign employers withholding final settlement and return airfare upon contract completion.", 
         "Lodge complaint with Embassy First Secretary (Labor), Ministry of Labor grievance", "Returning home empty-handed after years of labor"),
        ("Work Visas & Employment", "Repatriating the body of a deceased migrant worker from abroad", 
         "Families face confusing bureaucratic procedures across foreign morgues, embassies, and airlines.", 
         "Foreign death certificate, embalming certificate, Embassy NOC, Wage Earners' Welfare Board grant", "Body stranded in foreign mortuary for months"),

        # Tourist, Visitor & Business Visas
        ("Tourist & Travel Visas", "Applying for Schengen Tourist Visa (France, Italy, Germany)", 
         "High rejection rates occur due to vague travel itineraries and insufficient travel ties.", 
         "Confirmed flight reservation, verifiable hotel bookings, daily day-by-day itinerary, 3-year tax proof", "Visa denial stamp damaging future passport history"),
        ("Tourist & Travel Visas", "Applying for UK Standard Visitor Visa (Family / Tourism)", 
         "Unexplained deposits in bank accounts are classified as funds not genuinely available to applicant.", 
         "Full pay-slips matching bank deposits, employment leave sanction letter, property ownership", "Refusal under Immigration Rule V 4.2"),
        ("Tourist & Travel Visas", "Applying for US B1/B2 Tourist/Business Visa", 
         "DS-160 form inconsistencies with previous applications trigger immediate rejection.", 
         "DS-160 exact consistency, concise direct interview answers, demonstrating compelling home ties", "Denial under 214(b) without document inspection"),
        ("Tourist & Travel Visas", "Applying for Japan Tourist Visa through VFS Dhaka", 
         "Requires detailed itinerary schedule (Taizai Yoteihyo) and strict financial solvency.", 
         "Bank solvency certificate, tax return receipt, itinerary form with contact details", "Visa rejection with 6-month reapplication waiting period"),
        ("Tourist & Travel Visas", "Applying for Turkey e-Visa vs Sticker Visa", 
         "E-Visa is only valid for holders of valid Schengen, US, UK, or Irish visas.", 
         "Check prerequisite visa validity; apply for sticker visa through gateway if ineligible", "Turned away at airport check-in counter"),
        ("Tourist & Travel Visas", "Applying for Thailand Tourist Visa (Sticker vs e-Visa)", 
         "Requires bank statement with minimum 6-month balance and company letterhead leave approval.", 
         "Bank statement with minimum 150,000+ BDT per person, round-trip ticket, confirmed hotel", "Application rejected or delayed past flight date"),
        ("Tourist & Travel Visas", "Obtaining Dubai (UAE) 30/60-day Tourist Visa", 
         "Immigration periodically suspends or tightens tourist visas for specific passport categories.", 
         "Apply via GDRFA / ICP authorized travel partner, return ticket, sufficient USD cash", "Visa rejection without refund of visa fees"),
        ("Tourist & Travel Visas", "Applying for Singapore Entry Visa through authorized local agents", 
         "Singapore does not accept direct individual tourist applications; requires local sponsor or agent.", 
         "ICA-authorized agent submission, Form 14A, letter of introduction (V39A) if available", "Scammed by unauthorized online agencies"),
        ("Tourist & Travel Visas", "Applying for Malaysia e-Visa (SEV)", 
         "Uploading blurry passport scans or non-compliant studio photos causes rejection.", 
         "35x50mm white background photo without border, confirmed return flight, hotel booking", "Delayed approval resulting in missed flight"),
        ("Tourist & Travel Visas", "Handling visa rejection appeal or administrative review", 
         "Reapplying immediately with the same documents leads to automatic consecutive rejections.", 
         "Analyze refusal letter reasons, gather fresh documentary rebuttal, address root doubt", "Building a toxic record of multiple visa refusals"),

        # Airport Procedures & Flying
        ("Flights & Airports", "Avoiding airport offloading by Immigration Police at HSIA Dhaka", 
         "First-time travelers on visit visas are frequently interrogated and offloaded on trafficking suspicion.", 
         "Carry original return ticket, hotel booking, sufficient cash endorsement, company leave letter", "Missed flight, lost ticket fare, and humiliation"),
        ("Flights & Airports", "Baggage Customs Rules: Bringing gold, electronics, and alcohol to Bangladesh", 
         "Bringing gold bars or exceeding allowance of 117 grams passenger jewelry triggers confiscation and arrest.", 
         "National Board of Revenue (NBR) baggage baggage schedule rules, declaring excess goods at red channel", "Arrest for smuggling and seizure of precious goods"),
        ("Flights & Airports", "Transit Visa rules during international layovers (India, Gulf, Schengen, UK)", 
         "Changing terminals or self-transferring luggage in transit countries requires a transit visa.", 
         "Check if bags are checked through to final destination; verify airport airside transit rules", "Deported back from transit hub at personal expense"),
        ("Flights & Airports", "Dual Currency Passport Endorsement at bank", 
         "Using credit/debit card abroad without bank endorsement results in immediate transaction decline.", 
         "Visit bank branch with valid passport and visa, endorse annual quota (up to $12,000 USD)", "Stranded in foreign country with zero access to money"),
        ("Flights & Airports", "Web check-in and selecting seats without paying extra fees", 
         "Airlines open free seat selection 24-48 hours before departure during web check-in.", 
         "Log in exactly when 24h window opens, download digital boarding pass to mobile wallet", "Separated from family or assigned middle seat near toilet"),
        ("Flights & Airports", "Handling lost or damaged checked baggage at destination airport", 
         "Leaving baggage hall without filing Property Irregularity Report (PIR) forfeits airline liability.", 
         "File PIR at airline baggage counter before customs exit; keep baggage tag stub", "Lost luggage permanently with zero airline compensation"),
        ("Flights & Airports", "Claiming compensation for flight delays and cancellations under EU261", 
         "Flights originating in EU or on EU carriers qualify for up to 600 EUR cash compensation.", 
         "Keep boarding passes, note delay duration, file direct claim on airline portal", "Missing out on hundreds of Euros in mandatory compensation"),
        ("Flights & Airports", "Traveling abroad with prescription narcotics or controlled medications", 
         "Medications like sleeping pills, tramadol, or ADHD drugs are illegal in UAE, Japan, or Singapore.", 
         "Doctor's English prescription, original packaging, pharmacy receipt, embassy approval if required", "Arrest and imprisonment for drug smuggling"),
        ("Flights & Airports", "Carrying raw food, seeds, or plants through international customs", 
         "Countries like Australia, USA, and New Zealand impose massive fines for undeclared bio-matter.", 
         "Always tick 'YES' on customs declaration form for any food items; avoid fresh fruit/meat", "Immediate 1,000+ USD fines or visa revocation"),
        ("Flights & Airports", "Airport lounge access via credit cards (Priority Pass vs LoungeKey)", 
         "Supplementary cards or foreign airport visits may incur unexpected guest charges.", 
         "Check specific bank complimentary lounge visit limits, activate international roaming", "Surprise $32+ USD charges per person on credit card statement"),

        # Living Abroad & Expatriate Formalities
        ("Expat & Living Abroad", "Registering with Bangladesh Embassy / High Commission in host country", 
         "Unregistered expats face severe delays when renewing passports or needing consular rescue.", 
         "Embassy citizen consular portal registration, host country residence permit copy", "Inability to get emergency evacuation or consular support"),
        ("Expat & Living Abroad", "Renewing Bangladesh Passport abroad via MRP / e-Passport center", 
         "Embassies often have 3-6 month appointment backlogs for biometric e-passport renewals.", 
         "Book embassy appointment 6 months before passport expiry; verify NID/BRC match", "Losing host country legal residence status due to expired passport"),
        ("Expat & Living Abroad", "Sending money home legally via official banking channel (Wage Earners' Remittance)", 
         "Using illegal 'Hundi' channels risks money laundering prosecution and loses 2.5% govt cash incentive.", 
         "Use authorized exchange houses / bank transfer, verify 2.5% incentive credit, keep receipts", "Funds seized by law enforcement and bank account frozen"),
        ("Expat & Living Abroad", "Applying for Dual Nationality Certificate from Ministry of Home Affairs", 
         "Citizens acquiring foreign citizenship need certificate to retain Bangladesh rights and property ownership.", 
         "Application to Security Services Division, foreign naturalization certificate, proof of BD origin", "Losing inheritance and property rights in Bangladesh"),
        ("Expat & Living Abroad", "Obtaining 'No Visa Required' (NVR) seal for foreign passport", 
         "Allows foreign citizens of Bangladeshi origin to visit Bangladesh without visa indefinitely.", 
         "Surrender of BD passport copy / Birth certificate, embassy NVR application", "Stuck paying tourist visa fees and extensions every visit"),
        ("Expat & Living Abroad", "Executing a Power of Attorney abroad for property in Bangladesh", 
         "PoA signed abroad is invalid in Bangladesh unless executed before Consul and attested by MOFA Dhaka.", 
         "Sign in front of Consular Officer at Embassy, embassy seal, attestation at MOFA Segunbagicha", "Deed rejected by Sub-registrar in Bangladesh"),
        ("Expat & Living Abroad", "Opening a Non-Resident Foreign Currency Deposit (NFCD) account", 
         "Allows expatriates to keep foreign currency savings with high tax-free interest yields.", 
         "Work visa copy, salary certificate, initial foreign currency remittance", "Missing out on high interest rates and tax-exempt remittance"),
        ("Expat & Living Abroad", "Handling emergency loss of passport in a foreign country", 
         "Cannot board return flight without emergency travel document (Outpass / Travel Permit).", 
         "Local police report, visit Bangladesh Embassy for Emergency Travel Permit, airline rebooking", "Trapped in foreign transit area with zero legal papers"),
        ("Expat & Living Abroad", "Registering birth of a child born to Bangladeshi parents abroad", 
         "Failure to register with embassy prevents child from obtaining Bangladesh citizenship and passport.", 
         "Foreign birth certificate, parents' marriage certificate, embassy consular registration", "Difficulties claiming inheritance or dual citizenship later"),
        ("Expat & Living Abroad", "Repatriating personal effects under Baggage Rules when permanently moving back", 
         "Returning expats with 2+ years abroad can import household goods duty-free.", 
         "Transfer of Residence (TR) declaration, continuous stay proof, shipping bill of lading", "Massive customs duties assessed on personal used furniture")
    ]
    
    for item in items:
        if len(item) == 5:
            sub, title, prob, check, risk = item
            dont = prob
        elif len(item) == 6:
            sub, title, prob, dont, check, risk = item
        add(cat, sub, title, prob, dont, check, risk)

print("Immigration module ready.")
