"""
Expansion module containing comprehensive datasets to reach 1,000 unique real-world scenarios.
"""

def get_tech_expansion():
    return [
        ("Monitors", "Detecting IPS Backlight Bleed vs IPS Glow on gaming monitor", 
         "IPS glow shifts with viewing angle, but backlight bleed is a permanent physical bezel defect.", 
         "Test in pitch black room at 100% brightness; photograph from 2 meters away; demand replacement", "Stuck with distracting cloudy bright patches during dark movies/games"),
        ("Monitors", "Verifying DisplayPort 1.4 vs 2.1 cable bandwidth for high refresh rates", 
         "Cheap uncertified DisplayPort cables cause random black screen flickering and audio dropouts.", 
         "Look for VESA certified DP80 / HBR3 cable logo; verify 10-bit color support at 165Hz", "Intermittent display cutoffs during intense gaming"),
        ("Monitors", "Choosing between Matte vs Glossy vs Anti-Glare screen coatings", 
         "Heavy matte coatings make text look grainy and wash out perceived contrast in daylight.", 
         "Match room ambient lighting: glossy for dark rooms; light anti-reflective for bright office", "Eye strain and blurry text when reading code/documents"),
        ("Monitors", "Testing for Pulse-Width Modulation (PWM) screen flicker at low brightness", 
         "Monitors using low-frequency PWM dimming cause severe eye strain, migraines, and fatigue.", 
         "Point smartphone camera at screen at 240fps slow-motion; verify 'Flicker-Free' TUV certification", "Chronic headaches and burning eyes after 2 hours of work"),
        ("Monitors", "Calibrating monitor color with hardware colorimeter (Spyder / X-Rite)", 
         "Factory monitor profiles oversaturate colors, ruining print and professional video outputs.", 
         "Use Datacolor Spyder / Calibrite colorimeter; calibrate to 6500K color temp, 2.2 gamma, 120 cd/m²", "Prints coming out dull, green-tinted, or dark"),

        ("Audio Gear", "Diagnosing High-Impedance Headphone power requirements (Ohm and Sensitivity)", 
         "Plugging 250-Ohm Beyerdynamic headphones into a phone results in thin, whisper-quiet sound.", 
         "Check headphone sensitivity (dB/mW) and impedance; buy dedicated headphone DAC/Amp (e.g. FiiO/Schiit)", "Wasting money on high-end headphones without adequate amplification"),
        ("Audio Gear", "Open-Back vs Closed-Back Headphones for recording and mixing", 
         "Open-back headphones leak sound into vocal microphones, causing incurable recording bleed.", 
         "Use Closed-back for vocal recording / commuting; Open-back for wide soundstage mixing in quiet rooms", "Microphone picking up headphone click-track backing audio"),
        ("Audio Gear", "Selecting IEMs (In-Ear Monitors): Balanced Armature vs Planar vs Dynamic Drivers", 
         "Planar IEMs require powerful DAC output and can sound harsh if tip seal is improper.", 
         "Test various ear-tip sizes (foam vs silicone) for acoustic bass seal; verify source output impedance", "Zero bass response and piercing treble fatigue"),
        ("Audio Gear", "Choosing between XLR vs USB microphone setups for podcasting", 
         "USB mics lack analog gain headroom and cannot connect to multi-person mixing boards.", 
         "Choose USB for simple solo streaming; choose XLR with audio interface for multi-mic setups", "Having to throw away USB mics when expanding to 2 hosts"),
        ("Audio Gear", "Preventing Audio Latency in Digital Audio Workstations (DAW) on Windows", 
         "Standard Windows MME/DirectSound drivers cause 200ms delay, making live recording impossible.", 
         "Install dedicated OEM ASIO driver; set buffer size to 64 or 128 samples at 48kHz", "Audio recording out of sync with metronome"),

        ("PC Components", "Selecting Motherboard VRM (Voltage Regulator Module) for power-hungry CPUs", 
         "Cheap motherboards with uncooled 4-phase VRMs overheat and throttle Core i9/Ryzen 9 CPUs.", 
         "Check VRM heatsink presence, MOSFET amperage rating (minimum 60A DrMOS power stages)", "CPU throttling down to 2.5 GHz under rendering load"),
        ("PC Components", "Choosing Air Cooler vs AIO Liquid Cooler longevity and pump failure", 
         "AIO liquid cooler pumps fail silently after 3-5 years, causing instant 100°C CPU overheating.", 
         "Choose dual-tower air cooler (e.g. Thermalright Peerless Assassin) for zero leak risk and infinite lifespan", "Liquid cooler leaking fluid onto GPU or silent pump death"),
        ("PC Components", "Thermal paste application patterns (Dot vs X vs Spread method)", 
         "Putting too little paste leaves hot spots on large multi-die CPUs like AMD Ryzen or Threadripper.", 
         "Use the X-pattern with corner dots or full spatula spread to ensure 100% IHS coverage", "CPU core hitting 90°C while cooler remains lukewarm"),
        ("PC Components", "Cable Management and avoiding 12VHPWR 16-pin GPU cable melting", 
         "RTX 40-series 16-pin connectors melt and catch fire if cable is bent sharply within 35mm of plug.", 
         "Ensure connector is fully seated with audible click, zero gap between plug and socket, no tight lateral bend", "Melted 2,000 USD graphics card power socket and fire hazard"),
        ("PC Components", "Selecting PC Case Fan airflow: Static Pressure vs Airflow fans", 
         "Using low-pressure airflow fans against dense radiators or dust filters chokes airflow.", 
         "Use High Static Pressure fans (P-series) for radiators and dense mesh; High Airflow (F-series) for exhaust", "PC case turning into a hot oven with soaring GPU temps"),

        ("Smart Home & Gadgets", "Setting up Zigbee / Z-Wave Smart Home Hub vs Wi-Fi IoT devices", 
         "Connecting 50 Wi-Fi smart switches crashes consumer home routers and congests 2.4 GHz band.", 
         "Use dedicated Zigbee 3.0 coordinator with Home Assistant to keep smart devices on local mesh", "Home Wi-Fi constantly disconnecting on laptops and phones"),
        ("Smart Home & Gadgets", "Automating Smart Curtains and calculating motor torque for heavy drapes", 
         "Weak budget curtain motors jam and strip plastic gears when pulling heavy velvet drapes.", 
         "Calculate curtain fabric weight (kg); choose high-torque Tuya/Aqara track motor with manual pull backup", "Motor burning out or getting stuck half-open"),
        ("Smart Home & Gadgets", "Selecting Smart Door Lock: Fingerprint vs NFC vs Mechanical Key override", 
         "Electronic locks without external USB emergency power terminals lock you out when batteries die.", 
         "Ensure physical brass cylinder key override and Type-C 5V jumpstart port at bottom of lock", "Locked out of apartment at midnight with dead lock battery"),
        ("Smart Home & Gadgets", "Configuring Smart Thermostat / AC IR Blaster with temperature sensors", 
         "Relying on built-in AC thermometer measures high ceiling heat instead of bed-level temperature.", 
         "Place wireless Zigbee temperature sensor at bed height; link via automation to IR blaster", "Freezing at night or sweating while AC cycles prematurely"),
        ("Smart Home & Gadgets", "Smart Video Doorbell: Cloud subscription fee vs local MicroSD/RTSP storage", 
         "Brands like Ring charge mandatory monthly cloud fees; footage is inaccessible without subscription.", 
         "Choose Eufy or Reolink with local chime SD card storage and RTSP/ONVIF network streaming", "Paying 10 USD/month forever just to see who rang the door"),

        ("Printers & Peripherals", "Inkjet vs Ink Tank vs Monochrome Laser Printer cost per page", 
         "Cheap cartridge inkjets cost 15 BDT per page and printheads dry out if unused for 2 weeks.", 
         "Choose Monochrome Laser for text (0.5 BDT/page) or Continuous Ink Tank for high-volume color", "Spending 3,000 BDT on replacement cartridges every 100 pages"),
        ("Printers & Peripherals", "Mechanical Keyboard switches: Linear vs Tactile vs Clicky vs Hall Effect", 
         "Buying loud blue clicky switches makes typing unbearable for colleagues in office environments.", 
         "Red linear for quiet gaming; Brown tactile for typing; Magnetic Hall Effect for rapid trigger gaming", "Co-workers complaining about deafening typing clicks"),
        ("Printers & Peripherals", "Ergonomic Vertical Mouse vs Trackball for Carpal Tunnel relief", 
         "Standard flat mice force forearm into pronated twist, compressing the median nerve.", 
         "Use 57-degree vertical ergonomic mouse (e.g. Logitech MX Vertical) to keep arm in neutral handshake position", "Chronic wrist numbness, tingling, and carpal tunnel surgery"),
        ("Printers & Peripherals", "Flatbed vs Document Sheet-Feed Scanner for archiving", 
         "Feeding old fragile historical documents into automatic sheet feeders tears and jams papers.", 
         "Use high-resolution CIS/CCD flatbed scanner for receipts/photos; sheet-feeder for fresh legal sheets", "Ripped original birth certificates and irreplaceable family deeds"),
        ("Printers & Peripherals", "UPS (Uninterruptible Power Supply) Line-Interactive vs Online Double-Conversion", 
         "Line-interactive UPS has an 8-12ms transfer delay that shuts down sensitive PC gaming power supplies.", 
         "Buy pure sine wave Online Double-Conversion UPS with zero transfer time for workstation/servers", "Workstation restarting and losing 4 hours of unsaved 3D rendering"),

        ("Gaming Consoles & Retro", "PS5 / Xbox Series X Liquid Metal oxidation and horizontal vs vertical placement", 
         "Poorly applied liquid metal in early PS5 revisions could leak if standing vertically after drops.", 
         "Keep console well-ventilated on horizontal stand; dust out heatsink fin vents every 6 months", "APU dry spots causing overheating shutdowns during games"),
        ("Gaming Consoles & Retro", "Nintendo Switch Joy-Con analog stick drift fix (Hall Effect sticks)", 
         "Standard carbon potentiometer sticks wear down from friction, causing characters to walk on their own.", 
         "Replace factory sticks with Gulikit Hall Effect electromagnetic sensors that never wear out", "Inability to aim or control games due to severe drift"),
        ("Gaming Consoles & Retro", "Cleaning and replacing thermal paste on PlayStation 4 / Xbox One", 
         "Clogged heatsinks and dry thermal paste turn PS4 fans into a deafening jet engine sound.", 
         "Disassemble casing, clear dust carpet from heatsink fins, apply Arctic MX-6 paste and 1.0mm thermal pads", "Console shutting down with 'PS4 is too hot' error message"),
        ("Gaming Consoles & Retro", "Setting up RetroArch emulation handheld (Anbernic / Miyoo Mini)", 
         "Stock MicroSD cards included with retro handhelds are counterfeit and corrupt within days.", 
         "Replace stock SD with genuine Sandisk/Samsung; flash OnionOS or GarlicOS firmware", "Losing 40 hours of Pokemon / RPG game save files"),
        ("Gaming Consoles & Retro", "HDMI 2.1 eARC Audio Passthrough to Home Theater Soundbar", 
         "Connecting console directly to older soundbar introduces 200ms audio lip-sync delay.", 
         "Connect console directly to TV HDMI 2.1 port; pass Dolby Atmos back via eARC port to soundbar", "Gunshot sound firing half a second after pulling trigger")
    ]

def get_home_expansion():
    return [
        ("Kitchen", "Cast Iron Skillet seasoning and preventing rust", 
         "Washing cast iron with harsh dish soap and leaving it wet dissolves seasoning and causes rust.", 
         "Dry immediately on stove heat, wipe with thin coat of high-smoke-point oil (flaxseed/canola)", "Black rusty pan flaking metallic rust into food"),
        ("Kitchen", "Stainless Steel Tri-Ply Cookware: The water drop mercury test", 
         "Food sticks aggressively to stainless steel pans if they are not preheated to Leidenfrost temperature.", 
         "Preheat dry pan until water drops bead up and skate like mercury balls before adding oil", "Eggs and meat tearing and gluing permanently to bottom of pan"),
        ("Kitchen", "Chef Knife selection: Japanese VG-10 vs German Carbon Steel", 
         "Hard brittle Japanese knives (60+ HRC) chip and crack if used to hack through bone or frozen food.", 
         "Use flexible German steel (X50CrMoV15) for heavy butchering; thin Japanese steel for fine slicing", "Chipping a 150 USD Damascus blade on chicken bone"),
        ("Kitchen", "Gas Stove Burner cleaning: Unclogging yellow lazy flames", 
         "Yellow soot-producing flames mean clogged brass burner jets and dangerous carbon monoxide emission.", 
         "Boil brass burners in vinegar-baking soda solution; clear jet holes with thin copper wire", "Black soot coating outside of all pots; high gas wastage"),
        ("Kitchen", "Dishwasher installation: Water hardness and rinse aid settings", 
         "South Asian hard water leaves cloudy white calcium spots and etched glassware.", 
         "Set internal water softener salt valve according to municipal water hardness; use finish rinse aid", "Cloudy stained glasses and food residue baked onto plates"),

        ("Home Maintenance", "Fixing Running Toilet Flapper valve and silent water leak", 
         "A warped rubber flapper valve silently leaks 200 liters of water per day into the bowl.", 
         "Add 5 drops of food coloring into toilet tank; if color appears in bowl without flushing, replace flapper", "Massive water pump electricity bills and running out of overhead water"),
        ("Home Maintenance", "Sealing bathroom silicone grout against black mold (Aspergillus)", 
         "Standard silicone caulk turns black with toxic fungal mold within 6 months in humid bathrooms.", 
         "Scrape old caulk completely, clean with isopropyl alcohol, apply 100% anti-fungal sanitary silicone", "Disgusting black mold smelling musty and causing respiratory allergies"),
        ("Home Maintenance", "Painting Walls: Primer sealer coat vs 2 coats of topcoat paint", 
         "Painting directly on bare plaster without an acrylic primer sealer causes paint to bubble and peel.", 
         "Apply alkali-resistant exterior/interior wall primer, sand smooth with 120-grit, apply 2 coats", "Sheets of expensive paint peeling off like sunburned skin"),
        ("Home Maintenance", "Fixing squeaky door hinges with white lithium grease vs WD-40", 
         "WD-40 is a solvent that cleans grease; using it on hinges makes them squeak worse after 3 days.", 
         "Clean pin with WD-40, then coat with persistent heavy White Lithium Grease or silicone lubricant", "Loud agonizing door creaks waking up sleeping baby"),
        ("Home Maintenance", "Drilling through glazed ceramic and porcelain bathroom tiles", 
         "Using standard hammer drill on tiles cracks the entire tile into spiderweb fractures.", 
         "Place masking tape over mark, turn OFF hammer mode, use carbide spade tip or diamond core bit", "Cracking expensive imported bathroom wall tiles"),

        ("Furniture & Decor", "Identifying Genuine Top-Grain Leather vs Bonded / PU Faux Leather", 
         "Faux PU leather begins peeling and shedding plastic flakes (delamination) after 2 years.", 
         "Check unfinished suede backside, smell for rich earthy leather aroma, check water absorption", "Sofa peeling into thousands of black plastic flakes across carpet"),
        ("Furniture & Decor", "Glass Table Safety: Annealed Float Glass vs Tempered Glass", 
         "Regular annealed glass tables shatter into dagger-sharp deadly shards when broken.", 
         "Insist on minimum 10mm-12mm Tempered Safety Glass with polished beveled edges", "Catastrophic deep arterial lacerations if someone leans or falls on table"),
        ("Furniture & Decor", "Hanging heavy 30 kg mirror on hollow brick / drywall wall", 
         "Hanging heavy mirrors with simple picture wire and single nail pulls chunks out of wall.", 
         "Use French Cleat aluminum interlocking brackets screwed directly into concrete / wall studs", "30 kg glass mirror crashing down in middle of night"),
        ("Furniture & Decor", "Wood Polish: French Spirit Shellac Polish vs PU Lacquer Polish", 
         "Traditional French spirit polish gets permanent white water-ring stains from hot tea cups.", 
         "Use two-pack Polyurethane (PU) clear coat for dining tables; French polish for antique cabinets", "White cloudy cup rings permanently ruining dining table shine"),
        ("Furniture & Decor", "Rooftop & Balcony Planters: Weight load capacity on RCC cantilevers", 
         "Loading balconies with hundreds of kilos of wet garden soil risks cantilever slab collapse.", 
         "Use lightweight potting mix (50% cocopeat + 25% perlite + 25% compost), place heavy pots over beams", "Structural cracks appearing along balcony joint line")
    ]

print("Expansion definitions loaded.")
