"""Land, Housing, Real Estate, and Construction (100 scenarios)"""

def populate_land(add):
    cat = "Land, Housing & Property"
    
    # Core Transactions
    items = [
        ("Land Purchase", "Buying agricultural land with crop-tenant (Borga) history", 
         "Tenants may have protected statutory tenancy rights preventing eviction.", 
         "Tenant relinquishment deed, land revenue records, physical survey", "Loss of physical possession"),
        ("Land Purchase", "Buying residential plot in an unapproved private housing scheme", 
         "Private housing projects must have environmental and development authority clearances.", 
         "RAJUK/CDA approval, layout plan clearance, wetland classification check", "Demolition or refusal of utility connections"),
        ("Land Purchase", "Buying land through a registered Power of Attorney (PoA)", 
         "PoA automatically terminates if the principal dies before deed execution.", 
         "Verify principal is alive, verify PoA registration at sub-registry, check specific sale authorization", "Void transaction and total loss of money"),
        ("Land Purchase", "Buying ancestral land from one brother without other co-sharers' consent", 
         "A co-sharer cannot sell a specific demarcated portion without mutual partition (Bonton-nama).", 
         "Registered Partition Deed (আপোষ বন্টননামা), joint survey, written NOC from all co-sharers", "Co-sharers filing pre-emption suit (হকশুফা)"),
        ("Land Purchase", "Buying land bordering river or water bodies (Char land)", 
         "Alluvion and diluvion laws (পয়স্তি ও শিকস্তি) often vest eroded or newly formed land back to the government.", 
         "Check Diara survey, AC Land clearance, riverbank demarcation records", "Government reclamation as Khas land"),
        ("Land Purchase", "Buying land under pending Civil Court suit (Lis Pendens)", 
         "Section 52 of Transfer of Property Act voids transfers during ongoing property lawsuits.", 
         "Check District Judge court records, Sub-registry search certificate for encumbrances", "Deed declared null and void by court"),
        ("Land Purchase", "Buying roadside commercial plot with potential road widening plans", 
         "Roads & Highways Department (RHD) may have notified acquisition line.", 
         "RHD master plan check, acquisition notice verification at DC office", "Land acquisition without compensation for illegal structures"),
        ("Land Purchase", "Buying hill or sloping land in hilly terrain", 
         "Strict environmental bans on cutting hills exist under Environment Conservation Act.", 
         "DoE (Department of Environment) NOC, Soil stability certificate", "Criminal prosecution for illegal hill cutting"),
        ("Land Purchase", "Buying industrial land within an export processing or economic zone buffer", 
         "BEZA or BEPZA buffer zones impose strict usage and zoning restrictions.", 
         "BEZA zoning master plan, Industrial clearance NOC, environmental categorization", "Inability to obtain factory license or gas/power"),
        ("Land Purchase", "Buying tea garden or rubber plantation grant land", 
         "Tea estate leases are specialized government leases that prohibit sub-division or residential conversion.", 
         "Tea Board approval, Ministry of Land clearance, original lease terms", "Immediate lease cancellation and state repossession"),
        
        # Apartments & Flats
        ("Apartment Purchase", "Buying an under-construction flat from a private developer", 
         "Developers often delay projects for years and hide structural deviations.", 
         "Developer REHAB membership, RAJUK/CDA approved sheet, milestone payment schedule, penalty clause", "Stuck life savings, delayed possession by 5+ years"),
        ("Apartment Purchase", "Buying a ready flat from a first-generation owner (Second-hand flat)", 
         "The seller must transfer both the apartment and the undivided proportion of land share.", 
         "Original registered deed, flat mutation in AC Land office, building association NOC, utility clearance", "Cannot register or mutate flat ownership"),
        ("Apartment Purchase", "Buying a flat on the top floor with exclusive roof rights", 
         "Roof access is by default a common facility for all owners unless explicitly registered in the master deed.", 
         "Master deed wording, building bylaws, building association resolution", "Lawsuits from neighbors and loss of roof access"),
        ("Apartment Purchase", "Buying an apartment where developer mortgaged project land to a bank", 
         "If the developer defaults on project loan, the bank can auction the entire building including flats.", 
         "Bank Non-Encumbrance Certificate (NEC), tripartite agreement, redemption deed", "Bank auctioning your home"),
        ("Apartment Purchase", "Buying an apartment with basement car parking space", 
         "Car parking spaces must be specifically numbered and demarcated in the sale deed.", 
         "Parking allotment letter, layout diagram attached to deed, association registry", "Neighbor disputes and inability to park"),
        ("Apartment Purchase", "Buying a studio apartment in a mixed commercial-residential building", 
         "Commercial utility tariffs and visitor regulations may disrupt residential living.", 
         "Approved building usage certificate, separate utility meters, noise zoning", "Exorbitant commercial electricity and gas bills"),
        ("Apartment Purchase", "Buying a flat with unauthorized cantilever/balcony extensions", 
         "Deviations from approved architectural plans violate building codes.", 
         "Compare actual built dimensions against RAJUK/CDA structural drawing", "Municipal notice and forced demolition of extensions"),
        ("Apartment Purchase", "Buying an apartment in a cooperative housing society", 
         "Cooperative bylaws require society committee approval before any transfer.", 
         "Society managing committee NOC, share certificate transfer, audit clearance", "Society refusing recognition or maintenance access"),
        ("Apartment Purchase", "Buying a duplex apartment created by joining two floors", 
         "Internal staircase modifications often compromise building structural integrity.", 
         "Structural engineer vetting, fire safety clearance, separate deeds for both units", "Building collapse hazard or fire authority sealing"),
        ("Apartment Purchase", "Purchasing an apartment without an Occupancy Certificate (OC)", 
         "Without an OC, a building is legally deemed unfit for human habitation.", 
         "City Corporation / Development Authority Occupancy Certificate", "Utility disconnection and eviction notice"),

        # Land Revenue & Verification
        ("Revenue & Records", "Applying for e-Mutation (ই-নামজারি) online", 
         "The official fee is fixed (approx 1,170 BDT), yet people pay thousands to middlemen.", 
         "mutation.land.gov.bd account, scanned deed, via-dalil, up-to-date khajna", "Extortion by touts and rejection due to missing via-deeds"),
        ("Revenue & Records", "Tracing chain of deeds (বায়া দলিল / Via-Dalil) for 30 years", 
         "A single missing link in deed transfers voids legal ownership chain.", 
         "Sub-registry index search, non-encumbrance certificate (NEC), record room copies", "Fraudulent title discovered after full payment"),
        ("Revenue & Records", "Reconciling CS, SA, RS, and BS/City Survey Khatians", 
         "Discrepancies in plot numbers or owner names across historical surveys indicate fraud or dispute.", 
         "Comparative Khatian ledger chart, Mouza map tracing, field verification", "Buying someone else's land due to surveyor error"),
        ("Revenue & Records", "Paying Land Development Tax (e-Khajna) online", 
         "Holding numbers must be linked to NID and digitized before tax can be deposited.", 
         "ldtax.gov.bd registration, holding entry, digital Dakhila download", "Accumulated interest penalties and auction for arrears"),
        ("Revenue & Records", "Verifying certified copy of Khatian from DC Record Room", 
         "Fake stamped parchhas are commonly fabricated by local brokers.", 
         "DC office QR code / barcode verification, volume ledger comparison", "Purchasing forged land documents"),
        ("Revenue & Records", "Correcting clerical errors in BS Khatian (Rev. Case / Section 31)", 
         "Incorrect names or shares in BS Khatian can only be corrected through Land Survey Tribunal or Assistant Commissioner (Land).", 
         "Civil suit or Section 31 application, original title deeds, historical records", "Perpetual title cloud preventing sale"),
        ("Revenue & Records", "Handling land listed under Vested Property (অর্পিত সম্পত্তি) Ka / Kha list", 
         "Buying Ka-listed vested property is strictly illegal and automatically vests in the government.", 
         "Check Upazila Nirbahi Officer (UNO) / AC Land Vested Property Gazette register", "Instant forfeiture of land to government"),
        ("Revenue & Records", "Verifying Waqf property status before transaction", 
         "Waqf properties cannot be sold or mortgaged without Administrator of Waqfs Bangladesh sanction.", 
         "Waqf Administrator office verification, Waqf enrollment register", "Deed declared null and void under Waqf Ordinance"),
        ("Revenue & Records", "Checking Section 4 Acquisition Notice on land", 
         "Once Section 4 notice is issued by DC office, any sale or construction is void.", 
         "District Commissioner Land Acquisition (LA) Branch register search", "Loss of money; compensation paid only to recorded owner"),
        ("Revenue & Records", "Demarcating physical boundary using digital GPS and Mouza sheet", 
         "Paper land area often does not match ground reality due to encroachment.", 
         "Independent government-certified Amin, 16-inch=1-mile Mouza map, total station survey", "Receiving less land than paid for"),

        # Tenancy & Rental
        ("Tenancy & Rental", "Drafting a legally enforceable residential tenancy agreement", 
         "Standard stationary shop agreements often lack vital termination, maintenance, and dispute clauses.", 
         "Stamp paper agreement, security deposit refund terms, annual escalation cap", "Arbitrary eviction or lost deposit"),
        ("Tenancy & Rental", "Filing police tenant verification form (CIMS)", 
         "Failing to register tenants with the local police station is a punishable offense under police regulations.", 
         "Citizen Information Management System (CIMS) form, tenant NID, passport photos", "Police detention or legal penalties during security raids"),
        ("Tenancy & Rental", "Recovering security deposit from an abusive landlord", 
         "Landlords frequently invent fake damage to deduct entire security deposits.", 
         "Initial inventory checklist with dated photos, written move-out notice, legal notice", "Forfeiture of 2-6 months' rent deposit"),
        ("Tenancy & Rental", "Evicting a commercial tenant who stopped paying rent", 
         "You cannot physically lock a tenant out without court order without committing criminal trespass.", 
         "Notice to Quit under Transfer of Property Act, suit for eviction in Small Causes Court", "Months of lost rent and criminal counter-charges"),
        ("Tenancy & Rental", "Renting to bachelor students / professionals", 
         "Building housing societies often enforce arbitrary, illegal bachelor bans.", 
         "Building society bylaws review, owner agreement with society permission clause", "Sudden harassment and forced midnight eviction"),
        ("Tenancy & Rental", "Renting commercial space for a restaurant or bakery", 
         "Requires high-voltage power sanction, commercial gas line, and Fire Service clearance.", 
         "Building commercial conversion certificate, load feasibility from electric utility", "Inability to open business after paying hefty advance"),
        ("Tenancy & Rental", "Sub-letting rooms or commercial space", 
         "Sub-letting without explicit written consent from the landlord violates tenancy law and invites instant eviction.", 
         "Written sub-lease consent clause, separate sub-metering agreement", "Immediate cancellation of lease and loss of business goodwill"),
        ("Tenancy & Rental", "Landlord abruptly shutting off water/electricity to force rent hike", 
         "Disconnection of essential services by landlord is an offense under Premises Rent Control Act.", 
         "File complaint with Rent Controller (Senior Assistant Judge Court), police GD", "Living in uninhabitable conditions"),
        ("Tenancy & Rental", "Drafting an escalation clause for a 10-year commercial lease", 
         "Uncapped inflation adjustments or vague renewal terms lead to expensive litigation.", 
         "Fixed percentage escalation every 3 years, arbitration clause, registered lease deed", "Sudden 100% rent demand or forced relocation"),
        ("Tenancy & Rental", "Renting a warehouse / godown for hazardous or chemical materials", 
         "Requires Department of Explosives permit and specialized industrial zoning.", 
         "Explosives license, Fire safety clearance, environmental category clearance", "Warehouse raid, heavy fines, or catastrophic fire liability"),

        # Construction, Remodeling & Infrastructure
        ("Construction", "Conducting geotechnical soil test before multi-story building", 
         "Soft clay or organic peat without proper pile foundation leads to building tilt or collapse.", 
         "Minimum 3-5 boreholes, SPT (Standard Penetration Test), certified soil report", "Foundation failure and building condemnation"),
        ("Construction", "Obtaining RAJUK / CDA / KDA building plan sanction", 
         "Deviations from setback rules (front, rear, side space) result in construction stoppage.", 
         "FAR (Floor Area Ratio) calculation, structural design vetted by certified engineer", "Demolition order or heavy compounding fines"),
        ("Construction", "Hiring a general contractor vs labor contract with self-procured materials", 
         "Contractors often substitute Grade 60 rod with Grade 40 and use adulterated cement.", 
         "Itemized bill of quantities (BOQ), batch testing of rebar and concrete cylinders", "Compromised structural strength and budget overrun"),
        ("Construction", "Installing rooftop solar net-metering system", 
         "Requires distribution utility inspection and bi-directional meter installation.", 
         "Utility net-metering policy clearance, solar panel tier-1 certification, inverter safety", "Power rejection or dangerous electrical backfeed"),
        ("Construction", "Sizing and installing an RCC septic tank and soak well", 
         "Inadequate septic capacity leads to sewage backup and contamination of ground water.", 
         "Percolation test, multi-chamber design, water table assessment", "Foul odor, continuous overflow, health department fines"),
        ("Construction", "Waterproofing an exposed concrete roof slab", 
         "Traditional lime terracing often cracks; polyurethane or elastomeric membrane required.", 
         "Surface preparation, primer coat, fiber-mesh reinforcement, flood ponding test", "Ceiling seepage, ruined plaster, corroded rebar"),
        ("Construction", "Installing a passenger elevator/lift in a private building", 
         "Requires Electric Inspector to the Government of Bangladesh (OIEG) safety clearance.", 
         "Elevator load test certificate, annual maintenance contract (AMC), emergency rescue device (ARD)", "Passenger entrapment accidents and legal liability"),
        ("Construction", "Designing fire exit staircase according to BNBC (National Building Code)", 
         "Fire doors must have minimum 2-hour fire rating with positive pressure ventilation.", 
         "Bangladesh National Building Code compliance, Fire Service NOC, panic bars", "Building sealed by Fire Service or fatal entrapment"),
        ("Construction", "Deep tube-well boring permission in urban areas", 
         "Unauthorized deep tube-wells are strictly banned by WASA to prevent aquifer depletion.", 
         "WASA clearance certificate, water quality testing (Arsenic, Salinity, Coliform)", "Borehole sealing and confiscation of pump equipment"),
        ("Construction", "Demolishing an old dangerous building safely", 
         "Demolition requires municipal permission and vibration monitoring for adjacent buildings.", 
         "Municipal demolition permit, third-party structural survey of neighbors, safety netting", "Collapse on neighboring structures and manslaughter charges"),

        # Property Disputes & Legal Recovery
        ("Disputes & Law", "Filing a Pre-emption Suit (হকশুফা মোকদ্দমা) against third-party buyer", 
         "Co-sharers have legal priority to buy adjacent ancestral land within statutory deadline.", 
         "File suit within statutory limitation under State Acquisition and Tenancy Act, deposit purchase price", "Permanent loss of contiguous family land"),
        ("Disputes & Law", "Defending against forged deed (জাল দলিল) created by land grabbers", 
         "Filing a suit under Specific Relief Act for cancellation of fraudulent deed.", 
         "Deed cancellation suit (Section 39 SR Act), handwriting expert verification, Sub-registry volume audit", "Loss of legal title to fraudsters"),
        ("Disputes & Law", "Removing an illegal boundary wall built by encroaching neighbor", 
         "Directly destroying the wall leads to criminal mischief charges; legal demarcation required.", 
         "Civil court demarcation suit, temporary injunction (Order 39 CPC), police assistance", "Violent physical altercation or reverse criminal case"),
        ("Disputes & Law", "Handling emergency Section 144 / 145 CrPC notice on land", 
         "Executive Magistrate can impose status quo to prevent imminent breach of peace over land.", 
         "Appear before Executive Magistrate with title documents, seek police report", "Arrest for violating prohibitory orders"),
        ("Disputes & Law", "Distributing property of a deceased parent among sons and daughters", 
         "Muslim or Hindu personal succession law governs exact share calculations.", 
         "Obtain Waris / Succession certificate from City Corporation / Union Parishad, registered Bonton-nama", "Lifelong family feud and frozen land transactions"),
        ("Disputes & Law", "Cancelling an irrevocable Power of Attorney (অপ্রত্যাহারযোগ্য আমমোক্তারনামা)", 
         "Requires formal registered cancellation deed or civil court declaration.", 
         "Public notice in daily newspaper, registered notice to attorney, Sub-registry notification", "Attorney selling land behind your back"),
        ("Disputes & Law", "Filing Land Survey Tribunal (LST) suit for BS survey errors", 
         "LST is the exclusive forum for challenging incorrect BS survey records.", 
         "Suit within limitation period, verified CS/SA/RS chain, witness affidavits", "Records permanently fixed in stranger's name"),
        ("Disputes & Law", "Resolving mutation appeal before Additional Deputy Commissioner (Revenue)", 
         "When AC Land rejects legitimate mutation or approves illegal mutation for rivals.", 
         "ADC Revenue appeal within 30 days, certified order sheet, hearing representation", "Title records remaining frozen"),
        ("Disputes & Law", "Recovering possession under Section 9 of Specific Relief Act", 
         "Dispossessed without consent can reclaim possession within 6 months irrespective of title.", 
         "File Section 9 suit within 6 months of dispossession, proof of previous possession", "Permanent dispossession requiring 10-year title suit"),
        ("Disputes & Law", "Executing a mutual land exchange deed (বদল দলিল)", 
         "Swapping plots with a neighbor requires formal valuation, stamp duty, and registration.", 
         "Equivalent valuation assessment, Sub-registry deed registration, dual mutation", "Tax fraud charges or one party reneging"),

        # Specialized Land & Housing Scenarios
        ("Specialized Land", "Buying property from an expatriate living in UK/USA", 
         "Expatriate Power of Attorney must be executed at Bangladesh Embassy and attested by MOFA.", 
         "Embassy execution seal, MOFA attestation, DC office verification within 4 months", "Deed rejected by Sub-registrar as forged"),
        ("Specialized Land", "Buying flat developed under joint venture land-sharing agreement", 
         "Verify owner's allocation vs developer's allocation in the registered joint venture deed.", 
         "Registered Joint Venture Agreement, Power of Attorney from landowner to builder", "Buying a flat that legally belongs to landowner, not builder"),
        ("Specialized Land", "Buying an abandoned property (পরিত্যক্ত সম্পত্তি) released by court", 
         "Court of Settlement releases require Gazette notification and Ministry of Housing clearance.", 
         "Ministry Gazette notification, Court of Settlement decree, physical inspection", "Eviction by Ministry of Housing eviction magistrate"),
        ("Specialized Land", "Buying tribal or Chittagong Hill Tracts (CHT) land", 
         "Non-tribal purchase is prohibited in CHT without Hill District Council Chairman permission.", 
         "Deputy Commissioner clearance, Hill District Council NOC, tribal headman certificate", "Deed cancelled and land seized under CHT regulations"),
        ("Specialized Land", "Converting agricultural land for industrial factory setup", 
         "Requires land class change (শ্রেণী পরিবর্তন) permission from DC and Ministry of Land.", 
         "Department of Agricultural Extension NOC, AC Land inspection, DC conversion order", "Factory closure, electricity disconnection, criminal penalty"),
        ("Specialized Land", "Buying property belonging to a minor (child under 18)", 
         "Parents cannot sell minor's property without District Judge's Court guardianship permission.", 
         "Guardianship Court permission order, proof of legal necessity for minor's welfare", "Sale declared void once the child turns 18"),
        ("Specialized Land", "Buying property from a registered Society, Trust or NGO", 
         "Requires Trust Deed authorization, NGO Affairs Bureau NOC, and board resolution.", 
         "Trust Deed powers review, NGOAB approval letter, executive committee resolution", "Deed declared ultra vires and cancelled"),
        ("Specialized Land", "Purchasing land adjacent to railway lines or highway bypass", 
         "Railway and Roads authorities maintain strict right-of-way buffer zones.", 
         "Railway estate officer clearance, buffer zone measurement from center-line", "Demolition during railway expansion without compensation"),
        ("Specialized Land", "Buying flat built on leased government land (e.g. RAJUK / CDA plot)", 
         "Transfer of leased plot requires formal permission and transfer fee payment to authority.", 
         "Authority permission letter, transfer fee challan, revised lease deed", "Registration rejected, flat sealed by development authority"),
        ("Specialized Land", "Constructing a boundary wall in an active conflict zone", 
         "Requires magistrate presence or police deputation if criminal threats exist.", 
         "Executive magistrate order, police deployment challan, certified Amin survey", "Violent assault or criminal charges for land grab"),

        # Tenancy & Society Operations
        ("Society & Living", "Setting up a registered Apartment Owners Association", 
         "Without a registered society, collecting service charges or repairing common assets is legally unenforceable.", 
         "Society registration under Societies Registration Act, drafting bylaws, bank account setup", "Rogue owners refusing service charges without recourse"),
        ("Society & Living", "Resolving building maintenance fund embezzlement by society committee", 
         "Requires independent audit and criminal breach of trust (Section 406/420 Penal Code) complaint.", 
         "Audited accounts, bank statements, general body meeting resolution, police complaint", "Embezzlement of millions in building funds"),
        ("Society & Living", "Dealing with commercial business operating in strictly residential flat", 
         "Running commercial coaching or godown in residential flat violates zoning and society bylaws.", 
         "Society warning letter, municipal zoning complaint, fire service inspection", "Fire risk, security breach, continuous disturbance"),
        ("Society & Living", "Installing electric vehicle (EV) charger in shared apartment parking", 
         "Requires dedicated sub-meter from building transformer and society NOC.", 
         "Electrician load calculation, fire safety box, society committee approval", "Transformer overload and fire hazard"),
        ("Society & Living", "Managing rooftop water tank cleaning and pipeline sanitation", 
         "Untreated overhead tanks cause widespread waterborne diseases in multi-story apartments.", 
         "Chlorine disinfection SOP, sediment flushing, water test lab report", "Typhoid, cholera, and contaminated drinking water"),
        ("Society & Living", "Handling persistent water leakage from upper floor bathroom into lower flat", 
         "Upper flat owner refusing repair can be compelled via civil suit for nuisance and damages.", 
         "Plumber damage report, written notice, civil court suit for mandatory injunction", "Ceiling collapse, ruined interior, continuous toxic mold"),
        ("Society & Living", "Terminating an incompetent private security agency in housing society", 
         "Requires contract termination clause compliance to prevent labor or legal backlash.", 
         "30-day notice, security guard background log, immediate handover of keys/badges", "Security guards protesting, locking gates, or theft"),
        ("Society & Living", "Setting up an organic rooftop garden without damaging roof waterproofing", 
         "Direct soil contact or roots penetrating concrete causes severe slab leakage.", 
         "Geotextile drainage cells, elevated planter beds, lightweight soil mix (cocopeat)", "Structural concrete degradation and ceiling leaks"),
        ("Society & Living", "Installing automated building intercom and RFID access gate", 
         "Requires power backup integration and emergency fire-door release override.", 
         "RFID tag database, battery backup, fire alarm emergency trigger link", "Tenants trapped inside during power/fire failure"),
        ("Society & Living", "Organizing emergency earthquake drill in a high-rise building", 
         "Residents panic and use elevators instead of fire stairs during real tremors.", 
         "Evacuation route map, floor captain assignment, assembly point demarcation", "Stampede and fatal injuries during seismic events"),

        # Rural & Agricultural Property
        ("Rural Property", "Purchasing rural fishery/pond (দীঘি বা পুকুর)", 
         "Excavating or altering natural water bodies is prohibited under Wetland Protection Act.", 
         "Fisheries department record, water body status in RS/BS Khatian, DC NOC", "Government filling order or fines under environmental law"),
        ("Rural Property", "Buying homestead land (ভিটা/বাস্তু জমি) in ancestral village", 
         "Verify that the pathway (হাঁটাহাঁটির রাস্তা) is legally recorded as public easement.", 
         "Easement right verification in Mouza map, road width verification", "Landlocked property with neighbor blocking road access"),
        ("Rural Property", "Installing a solar irrigation pump on agricultural land", 
         "Requires IDCOL / SREDA technical approval and groundwater depth assessment.", 
         "BADC clearance, IDCOL subsidy criteria, solar array tilt calculation", "Failed pump operation or groundwater depletion fines"),
        ("Rural Property", "Registering a mortgage with Bangladesh Krishi Bank for crop loan", 
         "Requires verified land ownership record (Dae-Mukti certificate).", 
         "Non-encumbrance certificate, updated Khatian, crop cultivation verification", "Loan rejection or predatory local loan-shark traps"),
        ("Rural Property", "Handling land erosion by river (শিকস্তি) and claiming land tax exemption", 
         "Citizens continue paying tax for submerged land unless formally recorded as Shikosti.", 
         "AC Land Shikosti report, Union Land Assistant Officer inspection, tax rebate order", "Paying tax for land that no longer physically exists"),
        ("Rural Property", "Reclaiming emerged char land (পয়স্তি) after river change", 
         "Emerged land does not automatically return to owner if 30 years have lapsed.", 
         "Payosti claim application to DC office, historical title records, revenue survey", "Government declaring it Khas land and distributing to others"),
        ("Rural Property", "Dealing with brick-kiln (ইটভাটা) damaging surrounding agricultural soil", 
         "Brick kilns within 1 km of agricultural land or residential settlements are illegal.", 
         "Department of Environment complaint, High Court writ compliance, DC mobile court", "Destruction of crop yield and toxic air pollution"),
        ("Rural Property", "Resolving ancestral graveyard (কবরস্থান) land demarcation", 
         "Graveyard land must be formally registered or dedicated as Waqf to prevent future sale.", 
         "Waqf dedicated deed, village committee resolution, GPS boundary marking", "Descendants selling gravesite land to developers"),
        ("Rural Property", "Purchasing agro-forestry orchard (বাগান জমি)", 
         "Tree count and timber maturity must be separately assessed alongside land value.", 
         "Forest Department tree felling permit rules, land revenue category", "Inability to cut and sell timber without forestry permits"),
        ("Rural Property", "Setting up commercial dairy / poultry shed on rural land", 
         "Requires Livestock Department registration and waste disposal biogas setup.", 
         "DLS registration, local Union Parishad trade license, biogas digestor", "Forced closure due to village odor/pollution complaints"),

        # Advanced Real Estate Mechanics
        ("Advanced Property", "Calculating Sub-registry stamp duty, source tax, and local fees", 
         "Official Mouza rate (মৌজা রেট) determines minimum taxable valuation.", 
         "Latest Mouza rate sheet, e-Challan payment, Sub-registry fee calculator", "Under-declaration penalty or overpaying middlemen"),
        ("Advanced Property", "Registering a Deed of Mortgage (বন্ধকী দলিল) for bank loan", 
         "Bank requires registered mortgage and irrevocable power of attorney to sell.", 
         "Title clearance report by bank panel lawyer, Sub-registry registered mortgage", "Hidden liens preventing future clearance"),
        ("Advanced Property", "Obtaining Deed Redemption / Reconveyance after loan repayment", 
         "Failing to get a registered redemption deed leaves bank charge on property forever.", 
         "Bank NOC, registered deed of release/redemption, return of original via-deeds", "Property flagged in CIB as mortgaged during resale"),
        ("Advanced Property", "Drafting an Agreement for Sale (বায়না দলিল / Bayna)", 
         "Under Registration Act, a Bayna deed must be registered within 30 days to be legally valid.", 
         "Registered Bayna deed, earnest money bank pay order, strict performance deadline", "Seller selling to another buyer for a higher price"),
        ("Advanced Property", "Filing Suit for Specific Performance when seller refuses to register deed", 
         "If seller takes Bayna money but refuses to register final deed, court can execute deed.", 
         "Suit under Section 12 SR Act, balance money deposited in court, registered Bayna deed", "Loss of Bayna advance money and property"),
        ("Advanced Property", "Handling real estate purchase under Benami (বেনামী লেনদেন)", 
         "Benami transactions are legally void; legal title belongs strictly to the named person.", 
         "Avoid Benami entirely; register only in genuine legal beneficiary's name", "Total loss of property to the named proxy"),
        ("Advanced Property", "Conducting search in Sub-registry Index 1 and Index 2 books", 
         "Checks whether seller secretly executed another deed for the same plot in the past 12 years.", 
         "Form 36 search application, year-by-year volume book inspection, official search slip", "Discovering double-selling after paying in full"),
        ("Advanced Property", "Procuring certified Mouza Map from Directorate of Land Records (DLRS)", 
         "Crucial for verifying actual plot shape, adjacent road width, and drainage channels.", 
         "DLRS Tejgaon / DC office map counter application, sheet number verification", "Buying plot that is narrower than depicted on paper"),
        ("Advanced Property", "Checking for pipeline right-of-way (Titas / Gas Transmission)", 
         "Underground high-pressure gas pipelines prohibit any construction within 25-50 feet.", 
         "GTCL / Titas pipeline route map, local utility survey", "Building demolition by gas authority with zero compensation"),
        ("Advanced Property", "Buying property sold through Court Auction (নিলাম বিক্রয়)", 
         "Requires checking if the auction decree has been appealed in High Court.", 
         "Court auction sale certificate (বায়না সার্টিফিকেট), possession delivery (দখলনামা)", "Original owner winning appellate reversal and claiming land")
    ]
    
    for item in items:
        if len(item) == 5:
            sub, title, prob, check, risk = item
            dont = prob
        elif len(item) == 6:
            sub, title, prob, dont, check, risk = item
        add(cat, sub, title, prob, dont, check, risk)

print("Land module ready.")
