"""Vehicles, Transport, Driving & Mobility (80 scenarios)"""

def populate_vehicles(add):
    cat = "Vehicles, Transport & Driving"
    
    items = [
        # Used Car Purchase
        ("Used Car Purchase", "Detecting flood damage in a second-hand Japanese reconditioned car", 
         "Waterlogged cars look pristine outside but have rusted wiring harness and molded insulation.", 
         "Check seat belt anchor rust, smell under carpet padding, check fuse box corrosion", "Complete electrical failure and ECM breakdown"),
        ("Used Car Purchase", "Detecting digital odometer rollback on a used sedan", 
         "Unscrupulous dealers roll back digital meters by 50,000+ km using cheap OBD tools.", 
         "Cross-reference original Japanese auction sheet, check steering wheel/pedal rubber wear", "Paying premium for an engine on the verge of failure"),
        ("Used Car Purchase", "Verifying authenticity of Japanese Auction Sheet (JAAI / USS)", 
         "Fake printed auction sheets with forged grades (e.g. Grade 4.5 instead of Grade R) are widespread.", 
         "Check chassis number on online auction verification portal (e.g., CarVX/Aleado)", "Buying an accidental repaired vehicle (Grade R/RA) as pristine"),
        ("Used Car Purchase", "Checking engine cylinder compression on a high-mileage car", 
         "Worn piston rings cause blow-by gas and power loss, requiring expensive engine overhaul.", 
         "Dry and wet compression tester gauge reading across all cylinders", "Engine seizing within months of purchase"),
        ("Used Car Purchase", "Inspecting chassis frame alignment and structural welding", 
         "Cars involved in major front or side collisions have cut-and-welded chassis rails.", 
         "Check factory spot welds under fender, paint thickness gauge meter on pillars", "Catastrophic structural failure in subsequent accident"),
        ("Used Car Purchase", "Testing Automatic / CVT transmission slipping during test drive", 
         "Delayed engagement or shudder during acceleration signals worn clutch packs or CVT belt wear.", 
         "Cold transmission fluid level check, stall test, hill-start shudder test", "Massive transmission replacement cost (1-3 Lakh BDT)"),
        ("Used Car Purchase", "Checking suspension components: Ball joints, bushings, and tie rods", 
         "Clunking over potholes means worn steering rack or torn rubber bushings.", 
         "Pry-bar inspection on control arms, visual check for grease leaks from boots", "Loss of steering control at highway speeds"),
        ("Used Car Purchase", "Verifying Hybrid vehicle battery pack health (e.g. Toyota Prius/Aqua)", 
         "Degraded NiMH/Lithium traction battery cells cost tens of thousands to replace.", 
         "OBD2 scanner with Dr. Prius app, cell voltage differential check under load", "Drastic fuel economy drop and hybrid system error lockout"),
        ("Used Car Purchase", "Checking for illegal engine or color change without BRTA endorsement", 
         "Replacing engine with different displacement or repainting without BRTA approval makes car illegal.", 
         "Match physical engine block stamp and color with BRTA Blue Book / Smart Card", "Vehicle seizure by police and heavy criminal penalty"),
        ("Used Car Purchase", "Transferring car ownership at BRTA (মালিকানা বদল)", 
         "Leaving car in previous owner's name creates legal liability in accidents and criminal cases.", 
         "Form T.O., Form T.T.O., seller's biometric verification, clearance of all unpaid token/fitness", "Previous owner revoking sale or police liability"),

        # Motorcycles & Scooters
        ("Motorbikes & Scooters", "Inspecting a used motorcycle engine for timing chain noise and smoke", 
         "Cold-start engine rattle indicates stretched cam chain; white smoke indicates burnt engine oil.", 
         "Cold start exhaust inspection, oil filler cap sludge check, rev-down decel check", "Piston seizure and costly top-end engine rebuild"),
        ("Motorbikes & Scooters", "Checking motorcycle frame chassis alignment after crash", 
         "Bikes that suffered severe head-on collisions have bent T-stem, misaligned forks, or bent swingarm.", 
         "Hands-free tracking test on straight road, wheel-string alignment test", "Severe wobble at high speed and deadly accident risk"),
        ("Motorbikes & Scooters", "Inspecting chain and sprocket tooth wear", 
         "Hooked teeth or loose chain can snap during acceleration, locking rear wheel.", 
         "Pull chain away from rear sprocket; check tooth symmetry and chain slack (25-35mm)", "Chain snapping, cracking crankcase, or high-speed crash"),
        ("Motorbikes & Scooters", "Testing scooter CVT variator rollers and drive belt", 
         "Worn CVT belt snaps without warning, leaving rider stranded on the highway.", 
         "Remove variator cover, check belt width with vernier caliper, inspect flat-spotted rollers", "Sudden breakdown and loss of drive"),
        ("Motorbikes & Scooters", "Checking motorcycle brake disc rotor warping and pad thickness", 
         "Pulsating front brake lever indicates warped rotor; metal-on-metal pad destroys caliper.", 
         "Micrometer rotor thickness check, visual brake pad lining check", "Complete brake fade during emergency stopping"),
        ("Motorbikes & Scooters", "Checking motorcycle electrical stator coil and regulator rectifier (RR unit)", 
         "Failing RR unit overcharges battery, boiling acid or leaving bike stranded with dead battery.", 
         "Multimeter voltage test at 5,000 RPM (should be 13.8V - 14.5V)", "Dead battery in remote area; fried ECU"),
        ("Motorbikes & Scooters", "Transferring motorcycle ownership with absentee seller", 
         "BRTA now strictly requires seller's biometric fingerprint presence at registration authority.", 
         "Seller must personally appear at BRTA circle office; verify original blue book", "Unable to transfer ownership; riding permanently with illegal paper"),
        ("Motorbikes & Scooters", "Inspecting tubeless tire tread depth and manufacturing date code", 
         "Tires older than 5 years suffer rubber hardening (dry rot) and zero wet grip.", 
         "Check 4-digit DOT date code (e.g. 2420 = 24th week of 2020), TWI wear indicators", "Loss of traction and skidding on wet roads"),
        ("Motorbikes & Scooters", "Buying an electric scooter / e-bike battery check (Lead Acid vs Li-ion)", 
         "Degraded lead-acid batteries fail within 6 months; lithium batteries require certified BMS.", 
         "Battery chemistry verification, BMS cut-off test, true range real-world test", "Battery dying after 15 km; expensive replacement"),
        ("Motorbikes & Scooters", "Checking motorcycle suspension fork oil seals and stanchion rust", 
         "Pitted fork stanchions tear oil seals, causing fork oil to coat front brake pads.", 
         "Compress front forks repeatedly; check chrome stanchions for scratches and oil leaks", "Contaminated front brakes and bottoming out suspension"),

        # BRTA Formalities & Documentation
        ("BRTA & Legal", "Renewing BRTA Motor Vehicle Fitness Certificate", 
         "Commercial and private vehicles must pass physical lane inspection at BRTA.", 
         "Headlight beam alignment, brake efficiency test, exhaust smoke test, fee e-Challan", "Heavy fine under Road Transport Act and vehicle impound"),
        ("BRTA & Legal", "Renewing BRTA Tax Token online via BSCAMS portal", 
         "Late payment attracts compounding monthly penalty interest.", 
         "Online portal payment, printing digital tax token, linking with bank account", "Police seizure during highway checkpoint"),
        ("BRTA & Legal", "Converting standard number plate to Retro-Reflective Digital Number Plate", 
         "Vehicles without RFID digital plates face confiscation and cannot clear fitness.", 
         "BRTA RFID installation appointment, original registration certificate", "Cannot cross highway toll plazas or clear annual fitness"),
        ("BRTA & Legal", "Obtaining International Driving Permit (IDP) from Automobile Association (AAB)", 
         "Required to drive or rent cars legally in foreign countries without taking local tests.", 
         "Valid BRTA Smart Driving License, passport, photos, AAB membership application", "Arrest for driving without license in foreign country"),
        ("BRTA & Legal", "Clearing unpaid police traffic e-Challans / Video cases", 
         "Video surveillance cases recorded by traffic cameras freeze BRTA renewal services.", 
         "DMP Traffic e-Challan portal search, online payment via bKash/card, payment slip", "Cannot renew tax token or transfer ownership"),
        ("BRTA & Legal", "Applying for duplicate Registration Certificate (Blue Book) after loss", 
         "Requires police GD and newspaper advertisement before BRTA issues duplicate.", 
         "Police GD copy, Thana non-recovery certificate, newspaper clipping, Form KHA", "Accused of running cloned or stolen vehicle"),
        ("BRTA & Legal", "Obtaining Route Permit for commercial transport (Bus/Truck/Pickup)", 
         "Operating outside designated regional transport route leads to vehicle seizure.", 
         "Regional Transport Authority (RTA) application, speed limiter certificate", "Vehicle impounded by mobile court"),
        ("BRTA & Legal", "Endorsing CNG / LPG conversion on vehicle registration", 
         "Running LPG/CNG without BRTA and Explosives Department endorsement is illegal.", 
         "Authorized conversion center certificate, cylinder hydrostatic test report, BRTA inspection", "Mobile court fine and catastrophic cylinder explosion risk"),
        ("BRTA & Legal", "Renewing Driving License from Professional to Non-Professional", 
         "Professional license requires dope test (drug test) clearance from government hospital.", 
         "Civil Surgeon medical fitness report, dope test report, biometric renewal at BRTA", "License suspended or rejected"),
        ("BRTA & Legal", "Handling vehicle seizure and bail from Police Thana / Court", 
         "When a vehicle is seized under Section 105 Road Transport Act after an incident.", 
         "Court surrender application (জিম্মায় মুক্তি), surety bond, vehicle inspection report", "Vehicle rotting in police dumping yard for years"),

        # Mechanical Diagnostics & Maintenance
        ("Maintenance & Repairs", "Diagnosing 'Check Engine Light' using an OBD-II scanner", 
         "Mechanics often clear error codes without fixing root catalytic/O2 sensor issues.", 
         "OBD2 scanner read freeze frame data, live fuel trim percentages, clearing pending codes", "Paying for wrong replacement parts; failing emissions"),
        ("Maintenance & Repairs", "Flushing engine coolant vs just topping up with tap water", 
         "Tap water causes internal radiator corrosion and water pump impeller erosion.", 
         "Use distilled water with 50/50 ethylene glycol coolant, air-bleed cooling system", "Engine overheating, blown head gasket, warped cylinder head"),
        ("Maintenance & Repairs", "Brake fluid replacement (DOT 3 vs DOT 4 vs DOT 5.1)", 
         "Brake fluid absorbs moisture from air over 2 years, drastically lowering boiling point.", 
         "Moisture tester pen, complete system bleed from furthest caliper to master cylinder", "Vapor lock and complete brake pedal sinkage on mountain descents"),
        ("Maintenance & Repairs", "Wheel balancing and 4-wheel laser alignment", 
         "Improper alignment causes rapid uneven tire wear and vehicle pulling to one side.", 
         "Camber, caster, and toe angle measurement printout", "Tires ruined within 5,000 km; poor highway stability"),
        ("Maintenance & Repairs", "Servicing car Air Conditioning (R134a vs R1234yf refrigerant)", 
         "Cheap mechanics inject flammable LPG gas into AC systems instead of certified freon.", 
         "Verify manifold gauge pressure, vacuum leak test, genuine R134a can verification", "Catastrophic dashboard fire or compressor explosion"),
        ("Maintenance & Repairs", "Diagnosing alternator charging system failure", 
         "A weak alternator drains battery, leaving car dead in the middle of traffic.", 
         "Multimeter check: battery resting (12.6V) vs running alternator (14.2V), diode ripple test", "Sudden stall in heavy traffic or nighttime highway"),
        ("Maintenance & Repairs", "Cleaning fuel injectors and throttle body", 
         "Clogged injectors cause rough idle, misfires, and high fuel consumption.", 
         "Ultrasonic injector bath test, spray pattern verification, idle relearn procedure", "Engine misfire and catalytic converter damage"),
        ("Maintenance & Repairs", "Inspecting serpentine drive belt and tensioner pulley", 
         "Cracked drive belt snaps, disabling alternator, power steering, and water pump.", 
         "Check for transverse cracks per inch; spin tensioner pulley to check for bearing growl", "Instant engine overheating and loss of power steering"),
        ("Maintenance & Repairs", "Replacing automatic transmission fluid (ATF) drain & fill vs flush", 
         "High-pressure flush on high-mileage transmissions dislodges clutch debris, ruining valve body.", 
         "Drain and fill with OEM-specified fluid (e.g. Toyota WS / Honda DW-1), replace filter", "Total transmission slippage and gearbox failure"),
        ("Maintenance & Repairs", "Preventing undercarriage rust with anti-corrosion coating", 
         "Coastal driving and road salt cause severe chassis floor perforation.", 
         "High-pressure steam wash, rust converter primer, rubberized undercoating spray", "Structural rust holes through floorboard"),

        # Emergencies, Accidents & Highway Driving
        ("Accidents & Safety", "Step-by-step Standard Operating Procedure after highway accident", 
         "Drivers panic and argue on road, exposing themselves to oncoming traffic.", 
         "Turn on hazard lights, place reflective triangle 50m behind, move passengers behind guardrail", "Secondary crash from behind; fatal pedestrian strikes"),
        ("Accidents & Safety", "Collecting evidence to file motor insurance comprehensive claim", 
         "Insurance companies reject claims if scene photos or police GD are missing.", 
         "Wide-angle accident scene photos, third-party vehicle details, police GD, surveyor report", "Insurance claim denial; paying 100% out of pocket"),
        ("Accidents & Safety", "Handling tire blowout at 100 km/h on an expressway", 
         "Slamming on the brakes during high-speed tire blowout causes immediate rollover.", 
         "Do not slam brakes; maintain firm grip on steering wheel, gently coast down, steer to shoulder", "Catastrophic rollover crash"),
        ("Accidents & Safety", "Dealing with an aggressive hostile mob after minor traffic collision", 
         "Exiting the vehicle immediately in a volatile area can lead to lynching.", 
         "Keep doors locked, record dashcam footage, drive calmly to nearest police station if threatened", "Physical assault and vehicle vandalism"),
        ("Accidents & Safety", "Jumper-starting a dead car battery safely", 
         "Connecting jumper cables in reverse order explodes battery or fries ECM computer.", 
         "Red to positive dead, red to positive live, black to live, black to unpainted engine ground", "Destroyed vehicle electronics (1-2 Lakh BDT)"),
        ("Accidents & Safety", "Escaping a vehicle submerged in water / canal", 
         "Water pressure prevents opening doors until water level equalizes inside.", 
         "Immediately open windows before electrical failure; use headrest steel pegs to break side window", "Drowning inside trapped cabin"),
        ("Accidents & Safety", "Extinguishing an engine compartment car fire", 
         "Opening the hood wide feeds oxygen to flames, creating a massive fireball.", 
         "Slightly crack the hood, discharge ABC dry chemical extinguisher through gap", "Severe facial burns and total vehicle destruction"),
        ("Accidents & Safety", "Towing an all-wheel-drive (AWD) car safely", 
         "Towing an AWD car with wheels on the ground destroys center differential within 1 km.", 
         "Strictly require flatbed tow truck; disengage electronic parking brake", "Differential and transmission locked and ruined"),
        ("Accidents & Safety", "Handling sudden brake failure while driving", 
         "Pumping brakes, downshifting gears, and gradual handbrake pull can stop car.", 
         "Rapidly pump brake pedal, downshift to lowest gear, use emergency friction scrub against embankment", "Fatal head-on collision"),
        ("Accidents & Safety", "Safe highway driving during dense winter fog", 
         "Using high beams in fog reflects light back into driver's eyes, causing whiteout blindness.", 
         "Use low beams and yellow fog lights, follow road lane marking reflectors, double follow distance", "Massive multi-car pileup"),

        # Specialized Transport & Heavy Vehicles
        ("Specialized Vehicles", "Buying a commercial pickup or mini-truck (e.g. Tata Ace/Mahindra)", 
         "Commercial vehicles have strict overloading and gross vehicle weight (GVW) limits.", 
         "BRTA fitness compliance, leaf spring suspension condition, differential whine test", "Frame cracking under load; heavy BRTA overloading fines"),
        ("Specialized Vehicles", "Hiring long-haul rent-a-car with driver for family trip", 
         "Unregistered private cars operating commercially lack passenger liability insurance.", 
         "Verify driver's professional driving license, check tire condition, agree on toll/gas terms", "Stranded midway; accident liability without insurance"),
        ("Specialized Vehicles", "Purchasing an auto-rickshaw / CNG commercial vehicle", 
         "In many cities, new commercial CNG registrations are strictly capped, requiring plate purchase.", 
         "Verify RTA registration quota, CNG meter calibration certificate, cylinder fitness", "Buying illegal cloned vehicle without operating permit"),
        ("Specialized Vehicles", "Inspecting agricultural tractor and power tiller before purchase", 
         "PTO shaft gears and hydraulic lift arms suffer severe wear in clay soil plowing.", 
         "Hydraulic lift test under load, PTO gear engagement, engine blow-by check", "Hydraulic failure during peak planting season"),
        ("Specialized Vehicles", "Shipping a car via railway cargo container or ferry", 
         "Improper wheel chocking causes vehicle to roll and crash inside container during transit.", 
         "Four-point ratchet wheel straps, fuel tank under 1/4th level, photographic inspection before loading", "Severe body damage and denting during transit"),
        ("Specialized Vehicles", "Installing aftermarket roof rack or luggage carrier legally", 
         "Modifying vehicle height or carrying goods on private passenger cars attracts police fines.", 
         "Check BRTA vehicle height specifications, ensure secure rain-gutter clamps", "Police seizure and fines under Road Transport Act"),
        ("Specialized Vehicles", "Installing car dashcam front and rear with parking surveillance", 
         "Hardwiring dashcam to wrong fuse drains car battery overnight.", 
         "Use hardwire kit with low-voltage cutoff box, connect to ACC and Constant fuse slots", "Dead battery every morning; voided wiring warranty"),
        ("Specialized Vehicles", "Installing high-intensity LED headlights without blinding oncoming drivers", 
         "Dropping LED bulbs into halogen reflector housings scatters glaring light into opposing traffic.", 
         "Use projector lenses with crisp horizontal cutoff line; align headlight beam angle", "Police ticket for dazzling headlights; causing night accidents"),
        ("Specialized Vehicles", "Soundproofing vehicle cabin with damping sheets (damping & deadening)", 
         "Applying cheap bitumen roofing sheets inside cabin emits toxic carcinogenic asphalt fumes.", 
         "Use certified butyl-rubber damping mats, closed-cell foam for acoustic absorption", "Noxious chemical odor in hot weather; peeling inside doors"),
        ("Specialized Vehicles", "Buying child safety car seat (ISOFIX vs seatbelt tether)", 
         "Holding a child on lap during crash crushes child between adult body and dashboard.", 
         "Verify ECE R44/04 or i-Size standard, check ISOFIX latch anchors in rear seats", "Fatal child ejection or crushing during collision"),

        # Road Trips, Cross-Border & Eco-Driving
        ("Mobility & Trips", "Planning a long-distance cross-country road trip (e.g., Dhaka to Cox's Bazar)", 
         "Highway breakdowns happen due to underinflated tires overheating and throwing tread.", 
         "Check cold tire PSI, spare tire inflation, toolkit, emergency triangle, coolant level", "Stranded on highway at midnight"),
        ("Mobility & Trips", "Navigating automated RFID toll plazas (e-Toll / Meghna-Gumti / Padma)", 
         "Entering automated RFID lane without tag or balance causes lane blockage and fines.", 
         "Fast-tag / RFID sticker registration, online toll account recharge", "Stuck at barrier; backing up against heavy truck traffic"),
        ("Mobility & Trips", "Driving an automatic car on steep mountain ghat roads (e.g. Sajek / Bandarban)", 
         "Relying solely on foot brakes on long downhill descents boils brake fluid, causing total brake loss.", 
         "Shift gear selector to 'L', 'S', or 'B' (low gear / engine braking), never neutral", "Brakes smoking and failing off cliff edge"),
        ("Mobility & Trips", "Recovering a car stuck in beach sand or deep mud", 
         "Spinning tires at high throttle digs vehicle down to the axles.", 
         "Lower tire pressure to 15 PSI to widen footprint; place floor mats under drive wheels", "Car submerged by incoming high tide"),
        ("Mobility & Trips", "Eco-driving techniques to improve fuel efficiency by 25%", 
         "Aggressive jackrabbit starts and rapid braking burn 30% more fuel.", 
         "Smooth linear throttle, maintaining 60-80 km/h sweet spot, minimizing AC idle running", "Spending thousands extra in unnecessary fuel bills"),
        ("Mobility & Trips", "Handling a traffic police stop at a highway checkpoint", 
         "Hostile behavior or missing mandatory papers leads to immediate impounding.", 
         "Politely present Smart Card, Tax Token, Fitness, and Driving License; know fine schedule", "Unfair harassment and unwarranted vehicle confiscation"),
        ("Mobility & Trips", "Installing GPS tracker with remote engine kill switch", 
         "Poorly installed tracker relays can cut engine power unexpectedly at 100 km/h.", 
         "Install dedicated relay on starter line instead of fuel pump; verify backup battery", "Car dying at high speed; electrical fire"),
        ("Mobility & Trips", "Choosing between Synthetic vs Mineral Engine Oil", 
         "Running thin 0W-20 oil in an old worn engine causes oil consumption and metal-on-metal wear.", 
         "Check vehicle manufacturer viscosity chart (e.g. 5W-30 vs 20W-50), verify API SP rating", "Engine failure or wasting money on wrong oil grade"),
        ("Mobility & Trips", "Bicycle commuting safety in chaotic urban traffic", 
         "Riding in blind spots of buses and trucks causes fatal squeeze accidents.", 
         "High-visibility reflective vest, front white and rear flashing red lights, defensive lane positioning", "Fatal collision with turning heavy vehicles"),
        ("Mobility & Trips", "Storing a vehicle unused for 6 months without damage", 
         "Leaving car parked for months ruins battery, flat-spots tires, and gums up fuel system.", 
         "Disconnect battery, inflate tires to 45 PSI, add fuel stabilizer, elevate on jack stands", "Seized brakes, ruined battery, varnished fuel tank")
    ]
    
    for item in items:
        if len(item) == 5:
            sub, title, prob, check, risk = item
            dont = prob
        elif len(item) == 6:
            sub, title, prob, dont, check, risk = item
        add(cat, sub, title, prob, dont, check, risk)

print("Vehicles module ready.")
