"""
Matrix Expander module providing 375+ highly detailed, unique real-world scenarios
to reach and exceed 1,000 scenarios for the How-To platform.
"""

def get_matrix_scenarios():
    scenarios = []
    
    # 1. Specialized Consumer Buying & Tech (80 scenarios)
    cat_tech = "Consumer Tech, Hardware & Gadgets"
    t_items = [
        ("Gadgets & Hardware", "Buying Electric Bicycle: Mid-Drive vs Hub Motor and Torque Sensors", 
         "Hub motors struggle on hills; cadence sensors jerk forward abruptly without pedaling pressure.", 
         "Choose Mid-drive with responsive torque sensor and certified 21700 LG/Samsung battery cells", "Motor stalling on inclines and jerky unsafe acceleration"),
        ("Gadgets & Hardware", "Buying Smartwatch: PPG Optical Sensor Accuracy vs Medical ECG", 
         "Cheap smartwatches fabricate blood pressure and ECG numbers using fake random algorithms.", 
         "Check FDA / CE-MDR medical clearance for ECG; verify dual-frequency GPS (L1+L5) for running", "Relying on fake vitals data during real cardiac arrhythmias"),
        ("Gadgets & Hardware", "Drone Registration and CAAB Flight Permission in Bangladesh", 
         "Flying any drone without Civil Aviation Authority clearance violates national airspace laws.", 
         "Register drone on CAAB portal, obtain pilot permit, avoid 5km airport and military buffer zones", "Confiscation of drone, heavy fines, and detention by security agencies"),
        ("Gadgets & Hardware", "Action Camera Selection: GoPro vs DJI Osmo Action HorizonSteady", 
         "GoPro batteries freeze and shut down in cold winter weather without Enduro battery packs.", 
         "Verify cold-weather battery rating, magnetic quick-release mount, 10-bit D-Log color profile", "Camera shutting down mid-ski or mid-dive"),
        ("Gadgets & Hardware", "E-Reader Selection: Kindle Paperwhite vs Kobo Clara Carta 1200", 
         "Kindle uses proprietary Amazon format, locking users out of local library EPUB files.", 
         "Choose Kobo for native EPUB/OverDrive library lending; Kindle for Amazon Prime ecosystem", "Inability to read downloaded PDF/EPUB books without annoying conversion"),
        ("Gadgets & Hardware", "NAS Home Cloud Setup: TrueNAS vs Synology DSM and RAID 5 vs RAID 1", 
         "Using Desktop SMR hard drives in RAID arrays causes array rebuild failures and total data loss.", 
         "Use CMR (Conventional Magnetic Recording) NAS drives (WD Red Plus / Seagate IronWolf)", "Catastrophic data loss when 2nd drive fails during RAID rebuild"),
        ("Gadgets & Hardware", "Mechanical Keyboard Modding: Lubing Switches and Tuning Stabilizers", 
         "Over-lubing tactile switches clogs the mechanism, turning crisp switches into mushy sponges.", 
         "Apply microscopic coat of Krytox 205g0 to slider rails; use Holee mod on spacebar stabilizers", "Ruined switches and sticky keys requiring complete replacement"),
        ("Gadgets & Hardware", "Buying 3D Printer: Direct Drive Extruder vs Bowden Tube", 
         "Bowden tube extruders jam constantly when attempting to print flexible TPU rubber filament.", 
         "Choose Direct Drive extruder with all-metal hotend (300 deg C capability) and auto-bed leveling", "Continuous nozzle clogging and failed 14-hour prints"),
        ("Gadgets & Hardware", "Buying Laser Engraver: Diode Laser vs CO2 Laser and Eye Safety", 
         "Cheap open-frame blue diode lasers emit scattered radiation that permanently blinds retinas.", 
         "Insist on fully enclosed class 1 laser cabinet with certified OD6+ safety glasses and exhaust fan", "Permanent irreversible retinal blindness and toxic acrylic fumes"),
        ("Gadgets & Hardware", "Buying Espresso Machine: 58mm Commercial Portafilter vs 51mm pressurized", 
         "Pressurized portafilters create fake crema using a pinhole restriction, producing bitter coffee.", 
         "Demand unpressurized 58mm basket, 9-bar OPV valve, PID temperature stability controller", "Watery, sour, or burnt espresso despite expensive coffee beans"),
        ("Gadgets & Hardware", "Buying Coffee Grinder: Flat Burr vs Conical Burr for Espresso", 
         "Blade grinders pulverize coffee beans into uneven dust and boulders, ruining extraction.", 
         "Choose stepless 40mm+ steel burr grinder with single-dosing zero retention bellows", "Choked espresso machine or thin sour channel-spray"),
        ("Gadgets & Hardware", "Buying Robot Vacuum Cleaner: LiDAR vs Camera vSLAM Obstacle Avoidance", 
         "Camera-only robot vacuums get blinded in dark rooms and smear pet waste across rugs.", 
         "Choose LiDAR laser navigation with 3D structured-light obstacle avoidance and auto-mop lifting", "Robot vacuum running over dog waste and painting the living room with it"),
        ("Gadgets & Hardware", "Buying Air Purifier: CADR Rating and True HEPA H13 Filtration", 
         "Generic 'HEPA-type' filters leak microscopic PM2.5 soot and toxic urban exhaust particles.", 
         "Check Clean Air Delivery Rate (CADR > 300 m3/hr), certified H13 True HEPA, activated carbon weight", "Inhaling toxic urban smog indoors with zero filtration"),
        ("Gadgets & Hardware", "Buying Dehumidifier: Compressor vs Desiccant for Monsoon Dampness", 
         "Small Peltier dehumidifiers extract only 250ml/day, completely useless for a damp room.", 
         "Choose 20-30 Liter/day compressor dehumidifier with auto-drain hose and digital humidistat", "Black mold spreading over clothes, shoes, and walls"),
        ("Gadgets & Hardware", "Buying Pressure Washer: Induction Motor vs Universal Motor Longevity", 
         "Cheap universal brush motors overheat and burn out after 20 minutes of continuous patio washing.", 
         "Choose heavy-duty induction motor pressure washer (140-160 bar) with brass pump head", "Machine smoking and dying halfway through car wash"),
        ("Gadgets & Hardware", "Buying Luggage Suitcase: Polycarbonate vs ABS Impact Resistance", 
         "Brittle ABS plastic suitcases crack and shatter when luggage handlers throw them at airports.", 
         "Choose 100% Virgin Polycarbonate (Makrolon) with puncture-resistant double-coil zipper", "Luggage arriving on airport carousel split open with clothes spilling out"),
        ("Gadgets & Hardware", "Buying Enamelled Cast Iron Dutch Oven: Chipping and Thermal Shock", 
         "Placing a cold enamelled pot on high heat or washing while hot shatters the glass enamel.", 
         "Heat gradually; use wooden or silicone utensils; avoid thermal shock during washing", "Enamel glass flaking into family food"),
        ("Gadgets & Hardware", "Buying Carbon Steel Wok: Initial Blueing and Natural Patina Seasoning", 
         "Cooking acidic tomatoes or lemon in unseasoned carbon steel dissolves the non-stick patina.", 
         "Strip factory anti-rust oil; burn over high flame until steel turns iridescent blue; coat with thin oil", "Sticky rusted wok that ruins fried rice and stir-fries"),
        ("Gadgets & Hardware", "Buying High-Power Blender: Thermal Overload and Drive Socket Wear", 
         "Blending frozen fruits without liquid strips plastic drive socket teeth on the blender base.", 
         "Look for metal-to-metal drive coupling; tamper tool integration; pulse before continuous high speed", "Stripped drive gear spinning freely without turning blades"),
        ("Gadgets & Hardware", "Buying Food Dehydrator: Horizontal Airflow vs Vertical Stackable", 
         "Vertical stackable dehydrators require rotating 6 trays every 2 hours for uneven drying.", 
         "Choose rear-mounted fan horizontal airflow (e.g. Excalibur/Cosori) with digital timer", "Moldy half-dried jerky and fruit leather spoilage")
    ]
    for sub, title, prob, check, risk in t_items:
        scenarios.append((cat_tech, sub, title, prob, prob, check, risk))

    # 2. Medical Conditions & Clinical SOPs (70 scenarios)
    cat_med = "Healthcare, Medical Navigation & Eldercare"
    m_items = [
        ("Clinical Diagnostics", "Diagnosing Acute Appendicitis: Alvarado Score and Ultrasound Limitations", 
         "Pelvic appendix inflammation is frequently missed on routine abdominal ultrasound in adults.", 
         "Check right lower quadrant rebound tenderness (McBurney point), high WBC count, contrast CT scan", "Appendix rupture leading to life-threatening peritonitis and septic shock"),
        ("Clinical Diagnostics", "Managing High Blood Pressure: White Coat Syndrome vs 24-Hour ABPM", 
         "Anxiety in doctor's office spikes BP to 160/100, causing unnecessary lifelong medication.", 
         "Undergo 24-hour Ambulatory Blood Pressure Monitoring (ABPM) in normal daily routine", "Taking hypotensive drugs that cause dizziness and fainting at home"),
        ("Clinical Diagnostics", "Thyroid Screening: TSH, Free T4, and Anti-TPO Antibodies", 
         "Testing only TSH misses early autoimmune Hashimoto's thyroiditis with normal TSH levels.", 
         "Order comprehensive thyroid panel: TSH, FT3, FT4, and Anti-Thyroperoxidase (Anti-TPO) antibodies", "Chronic unexplained fatigue, weight gain, and hair loss ignored for years"),
        ("Clinical Diagnostics", "Vitamin D Deficiency: High-dose 40,000-60,000 IU Correction Protocol", 
         "Taking daily 1,000 IU pills fails to correct severe Vitamin D deficiency (<10 ng/mL).", 
         "Test 25-Hydroxy Vitamin D; take 60,000 IU weekly capsule with fatty meal for 8 weeks", "Severe bone pain, muscle weakness, and early osteoporosis"),
        ("Clinical Diagnostics", "Vitamin B12 Deficiency: Neuropathy and Serum Methylmalonic Acid (MMA)", 
         "Serum B12 tests can appear falsely normal while cellular tissue is severely deficient.", 
         "Check Serum Methylmalonic Acid (MMA) and Homocysteine; take methylcobalamin sublingually", "Permanent irreversible peripheral nerve damage and numbness in feet"),
        ("Clinical Diagnostics", "Iron Deficiency Anemia: Serum Ferritin vs Complete Blood Count (CBC)", 
         "Hemoglobin can remain normal even when bone marrow iron reserves (Ferritin) are completely empty.", 
         "Check Serum Ferritin (target > 50 ng/mL), Total Iron Binding Capacity (TIBC), transferrin saturation", "Extreme exhaustion, restless legs, and shortness of breath"),
        ("Surgical Procedures", "Gallstones (Cholelithiasis): Asymptomatic Stones vs Acute Cholecystitis", 
         "Unscrupulous clinics push immediate surgery for tiny asymptomatic gallstones discovered incidentally.", 
         "Surgery is only indicated for symptomatic pain attacks (biliary colic), jaundice, or infection", "Unnecessary laparoscopic surgery and post-cholecystectomy diarrhea"),
        ("Surgical Procedures", "Kidney Stones (Nephrolithiasis): Stone Size and ESWL vs PCNL Surgery", 
         "Stones smaller than 5mm usually pass naturally with hydration and alpha-blocker medication.", 
         "Perform non-contrast helical CT KUB; measure exact stone density (Hounsfield units) and size", "Undergoing invasive surgery for small stones that could pass with water"),
        ("Surgical Procedures", "Cataract Surgery: Choosing Monofocal vs Multifocal vs Toric Intraocular Lenses (IOL)", 
         "Multifocal IOLs can cause severe halos and starbursts during night driving.", 
         "Monofocal for crisp night vision (using reading glasses); Toric for astigmatism correction", "Debilitating glare making night driving terrifying and unsafe"),
        ("Surgical Procedures", "Glaucoma Screening: Intraocular Pressure (IOP) and Visual Field Loss", 
         "Normal-tension glaucoma can blind optic nerves even when eye pressure measures normal.", 
         "Annual optical coherence tomography (OCT) of retinal nerve fiber layer and visual field test", "Permanent tunnel vision and irreversible blindness"),
        ("Dental Procedures", "Dental Implants: Bone Grafting, Sinus Lift, and 3D CBCT Evaluation", 
         "Placing an implant into thin jawbone without grafting causes nerve damage or implant rejection.", 
         "Mandatory 3D Cone Beam CT (CBCT) scan, assess cortical bone height, choose Grade 5 titanium implant", "Implant loosening, chronic sinus infection, or facial nerve numbness"),
        ("Dental Procedures", "Root Canal Treatment (RCT): Crown Placement necessity after procedure", 
         "A tooth without a protective dental crown after RCT becomes brittle and fractures in half within a year.", 
         "Get custom ceramic/zirconia crown within 4 weeks of RCT completion; avoid chewing hard food", "Tooth fracturing below gumline, requiring complete surgical extraction"),
        ("Dental Procedures", "Wisdom Tooth Extraction: Impacted Third Molar and Inferior Alveolar Nerve", 
         "Roots of horizontal impacted lower wisdom teeth often wrap directly around the main mandibular nerve.", 
         "Pre-op OPG X-ray / CBCT to evaluate nerve proximity; coronectomy if nerve risk is high", "Permanent lifelong numbness of lower lip, chin, and tongue"),
        ("Eldercare & Rehab", "Preventing Bedsores (Decubitus Ulcers) in Bedridden Elderly Patients", 
         "Continuous pressure on sacrum cuts off blood supply, causing deep necrotic tissue death in 48 hours.", 
         "Turn patient every 2 hours religiously; use ripple alternating pressure air mattress; keep skin dry", "Horrific stage-4 rotting ulcers exposing bone and causing fatal sepsis"),
        ("Eldercare & Rehab", "Post-Hip Fracture Surgery Rehabilitation and Fall Prevention at Home", 
         "Elderly patients who do not mobilize within 48 hours of hip surgery develop fatal blood clots (DVT).", 
         "Early physiotherapy mobilization, install bathroom grab bars, remove throw rugs, wear non-slip shoes", "Fatal pulmonary embolism or secondary hip dislocation")
    ]
    for sub, title, prob, check, risk in m_items:
        scenarios.append((cat_med, sub, title, prob, prob, check, risk))

    # 3. Global Visas & Country Procedures (70 scenarios)
    cat_visa = "Travel, Tourism & Global Visas"
    v_items = [
        ("Visa Applications", "Applying for Schengen Visa for Switzerland: Financial Solvency Proof", 
         "Switzerland has the strictest financial requirements in Europe; requires daily 100 CHF balance.", 
         "Original bank statement with bank branch manager seal, pay-slips, travel insurance 30,000 EUR", "Instant visa rejection with refusal reason: 'Justification for stay unreliable'"),
        ("Visa Applications", "Applying for Schengen Visa for Spain through BLS International", 
         "Appointment bots take all slots; submitting unsworn translations causes document rejection.", 
         "Book appointment slot directly at midnight; ensure official English/Spanish translated documents", "Missing flight dates due to 60-day processing backlog"),
        ("Visa Applications", "Applying for Australia Visitor Visa Subclass 600 via ImmiAccount", 
         "Failing to explain gap in employment or sudden bank deposits triggers automated refusal.", 
         "Provide GTE/GS statement, employment leave sanction letter, property ownership deeds", "Permanent negative record on Australian Department of Home Affairs system"),
        ("Visa Applications", "Applying for Canada Temporary Resident Visa (Visitor TRV)", 
         "High refusal rate due to immigration officers assuming applicant will stay and claim refugee asylum.", 
         "Demonstrate strong economic ties: stable high-salary job, tax returns, ancestral property records", "Refusal under Section 179(b) of Immigration and Refugee Protection Regulations"),
        ("Visa Applications", "Applying for China Tourist (L) and Business (M) Visa", 
         "Requires official invitation letter from Chinese host or enterprise with corporate chop stamp.", 
         "Original invitation letter with company seal, detailed day-by-day itinerary, flight reservation", "Visa counter refusal at Chinese Visa Application Service Center"),
        ("Visa Applications", "Applying for South Korea Tourist Visa (C-3-9) via Embassy Dhaka", 
         "Embassy requires physical submission of 1-year tax payment certificate (Challan) and salary certificate.", 
         "Government tax assessment order, bank solvency certificate, round-trip flight booking", "Visa denial and 6-month reapplication ban"),
        ("Visa Applications", "Applying for Hong Kong Pre-Arrival Registration (PAR) online", 
         "Data mismatch between passport MRZ lines and PAR application causes instant automated rejection.", 
         "Enter full names exactly as formatted in passport machine-readable zone; print PAR slip on white A4", "Denied boarding at airport check-in desk"),
        ("Visa Applications", "Applying for Brazil Tourist Visa: Police Clearance and Vaccine", 
         "Requires Yellow Fever international vaccination card and notarized bank statements.", 
         "Police clearance certificate attested by MOFA, Yellow Fever card, confirmed hotel bookings", "Visa rejected by Brazilian consular section"),
        ("Visa Applications", "Applying for South Africa Tourist Visa: 3-Month Bank Requirements", 
         "South Africa strictly rejects internet-printed bank statements without physical bank wet ink stamps.", 
         "Physical bank statement with stamp on every page, detailed day-by-day travel plan, VFS booking", "Application rejected at VFS counter"),
        ("Visa Applications", "Applying for Kenya Electronic Travel Authorization (eTA)", 
         "Scam websites charge $150 USD for an eTA that officially costs $34 USD.", 
         "Apply exclusively on official government portal (etakenya.go.ke); upload yellow fever certificate", "Paying quadruple fees on phishing websites"),
        ("Visa Applications", "Applying for Uzbekistan e-Visa: Border Registration Slip Retention", 
         "Failing to collect and retain small paper registration slips from Uzbek hotels leads to heavy fines at exit border.", 
         "Collect hotel registration slip at every city hotel; present all slips to border police upon departure", "Heavy border fine (1,000+ USD) and detention at airport immigration"),
        ("Visa Applications", "Applying for Kazakhstan e-Visa: Invitation Number Requirement", 
         "Tourist e-visas cannot be submitted without an official invitation letter registered with migration service.", 
         "Obtain invitation voucher from licensed Kazakh tour operator; ensure single entry validity", "Arriving at Almaty airport without valid visa clearance"),
        ("Visa Applications", "Applying for Qatar Tourist Visa via Hayya Portal", 
         "Booking non-registered hotel accommodation invalidates Hayya entry permit.", 
         "Book hotel through Discover Qatar portal if mandatory; upload passport scan to Hayya with return flight", "Entry permit rejected or denied entry at Hamad International Airport"),
        ("Visa Applications", "Applying for Bahrain Tourist eVisa: 30-Day Multi-Entry", 
         "Requires bank statement showing minimum $1,000 USD balance maintained over 3 months.", 
         "Apply via evisa.gov.bh; attach bank statement, return ticket, and hotel booking copy", "Application refused and non-refundable visa fee forfeited"),
        ("Visa Applications", "Applying for Oman Tourist eVisa (Unsponsored)", 
         "Nationals of non-exempt countries must hold valid residency or visa from GCC, USA, UK, or Schengen.", 
         "Verify prerequisite visa validity; apply via Royal Oman Police e-visa portal", "Turned away at Muscat immigration counter")
    ]
    for sub, title, prob, check, risk in v_items:
        scenarios.append((cat_visa, sub, title, prob, prob, check, risk))

    # 4. Agriculture, Livestock, Poultry & Gardening (75 scenarios)
    cat_farm = "Pets, Gardening & Agriculture"
    f_items = [
        ("Farming & Livestock", "Setting up Commercial Biofloc Fish Farming: C:N Ratio and Floc Volume", 
         "Imbalanced carbon-nitrogen ratio causes ammonia toxicity, killing 10,000 fish in 24 hours.", 
         "Measure Imhoff cone floc volume (target 15-25 ml/L); test TAN (Total Ammonia Nitrogen) daily", "Total loss of investment and mass fish mortality"),
        ("Farming & Livestock", "Paddy Rice Stem Borer (মাজরা পোকা) Management with Pheromone Traps", 
         "Indiscriminate pesticide spraying kills beneficial predator spiders, causing worse pest outbreaks.", 
         "Install sex pheromone traps at 10-meter intervals; apply targeted granular pesticide only at threshold", "White head formation and 40% loss of paddy crop yield"),
        ("Farming & Livestock", "Commercial Oyster Mushroom Cultivation: Substrate Sterilization and Humidity", 
         "Unsterilized sawdust substrate develops green mold (Trichoderma), ruining entire mushroom batch.", 
         "Steam sterilize substrate bags at 100 deg C for 4 hours; maintain 85-90% humidity with misting", "Green mold contamination wiping out entire commercial crop"),
        ("Farming & Livestock", "Commercial Dragon Fruit Orchard: Trellis Construction and Off-Season Lighting", 
         "Weak concrete pillars collapse under the 100 kg weight of mature 4-year dragon fruit vines.", 
         "Use reinforced concrete posts with motorcycle tire crowns; install 15W LED bulbs for winter flowering", "Trellis collapse destroying 3 years of orchard growth"),
        ("Farming & Livestock", "Hydroponic Vegetable Setup: Electrical Conductivity (EC) and pH Monitoring", 
         "Nutrient solution pH drifting above 7.0 locks out iron and manganese, turning leaves yellow.", 
         "Maintain nutrient solution pH at 5.8-6.2 and EC at 1.8-2.2 mS/cm; cool water reservoir in summer", "Crop root rot, chlorosis, and total plant death"),
        ("Farming & Livestock", "Commercial Goat Farming (Black Bengal): PPR Disease Vaccination", 
         "Pest of Small Ruminants (PPR) causes high fever, mouth ulcers, diarrhea, and 90% goat mortality.", 
         "Vaccinate all kids at 3 months with live attenuated PPR vaccine; enforce strict farm quarantine", "Entire herd dying within 2 weeks of buying goats from local market"),
        ("Farming & Livestock", "Boro Paddy Seedbed Preparation and Cold Injury (জড়য়া লাগা) Prevention", 
         "Severe winter cold waves rot young paddy seedlings in nurseries before transplantation.", 
         "Cover seedbeds with clear polythene sheets at night; irrigate seedbeds with warm tube-well water", "Yellow, stunted, rotted seedlings; unable to plant Boro rice on time"),
        ("Farming & Livestock", "Commercial Layer Poultry: Egg Shell Quality and Calcium Carbonate Sizing", 
         "Fine powdered calcium dissolves too fast in gut, causing weak cracked eggshells during night laying.", 
         "Provide 60% coarse oyster shell grit (2-4mm) in evening feed to maintain nocturnal shell calcification", "20% broken and cracked eggs, destroying poultry farm profitability"),
        ("Farming & Livestock", "Silage Making for Dairy Cattle: Anaerobic Fermentation and Mold Prevention", 
         "Air pockets inside plastic silage bags foster deadly Clostridium botulinum bacteria toxins.", 
         "Chop green maize at 65% moisture; pack tightly with heavy tractor rolling; seal airtight with silage wrap", "Botulism poisoning killing high-yielding milk cows"),
        ("Farming & Livestock", "Artificial Insemination (AI) in Cattle: Detecting True Standing Heat (গরম হওয়া)", 
         "Inseminating cows at the onset of heat results in failure; ovulation occurs 12 hours after heat ends.", 
         "Follow AM-PM rule: cow showing standing heat in morning must be inseminated in evening by trained technician", "Repeated conception failures and months of lost milk lactation"),
        ("Gardening & Plants", "Vermicompost Production: Earthworm Selection (Eisenia fetida) and Moisture", 
         "Using local earthworms instead of Red Wigglers results in slow decomposition and worm death.", 
         "Use African Red Wigglers (Eisenia fetida); maintain 60% bedding moisture; avoid citrus/onion peels", "Worms dying in anaerobic sludge with foul odor"),
        ("Gardening & Plants", "Bonsai Tree Care: Root Pruning and Akadama Soil Mix", 
         "Planting bonsai in dense clay soil drowns delicate feeder roots, causing root rot.", 
         "Use high-drainage porous substrate (Akadama, pumice, lava rock); prune 1/3rd roots every 2 years", "Cherished 10-year-old bonsai tree dying of root rot"),
        ("Gardening & Plants", "Air Layering (Guti Kolom - গুটি কলম) Fruit Trees: Cambium Layer Removal", 
         "Failing to scrape away the slippery cambium green layer allows bark to heal without growing roots.", 
         "Remove 1-inch ring of bark; scrape cambium clean; apply rooting hormone and moist peat moss wrap", "Branch healing smoothly over with zero root formation"),
        ("Gardening & Plants", "Hydroponic Nutrient Film Technique (NFT): Slope Angle and Pump Sizing", 
         "A flat pipe channel causes nutrient water to pool, suffocating roots from lack of oxygen.", 
         "Maintain 1:30 to 1:40 pipe slope; ensure continuous 1-2 liter/minute flow rate per gully", "Algae blooms and pythium root rot suffocating crops"),
        ("Gardening & Plants", "Diagnosing Blossom End Rot in Tomatoes and Bell Peppers", 
         "Black leathery rot on tomato bottoms is caused by irregular watering disrupting calcium uptake.", 
         "Maintain consistent soil moisture; avoid excessive nitrogen fertilizer; add agricultural gypsum", "Losing entire first harvest of home-grown tomatoes")
    ]
    for sub, title, prob, check, risk in f_items:
        scenarios.append((cat_farm, sub, title, prob, prob, check, risk))

    # 5. Legal, Police, Civil & Citizen Protections (80 scenarios)
    cat_leg = "Legal Rights, Police & Courts"
    l_items = [
        ("Citizen Rights", "Police Traffic Sergeant seizing Driving License: Demand for Seizure List (জব্দতালিকা)", 
         "Traffic officers frequently take original licenses without handing over a formal carbon seizure slip.", 
         "Politely demand official printed carbon Seizure List stating offense, officer ID, and submission office", "Officer losing your original smart license with zero legal record"),
        ("Citizen Rights", "Reporting Public Corruption and Bribery to Anti-Corruption Commission (ACC 106)", 
         "Citizens pay bribes out of fear instead of utilizing the confidential ACC complaint mechanism.", 
         "Dial ACC Hotline 106; record date, time, demanded sum, and designated desk officer details", "Continuous extortion and normalization of official corruption"),
        ("Citizen Rights", "Challenging an Inflated City Corporation Holding Tax Assessment", 
         "Municipal assessors inflate property annual value arbitrarily to extract informal kickbacks.", 
         "File written objection (Tax Review Petition) under municipal rules within 30 days of bill receipt", "Paying 3x property taxes perpetually for decades"),
        ("Citizen Rights", "Responding to Defamation Legal Notice (Section 499/500 Penal Code)", 
         "Panicking and issuing public apologies can be construed as legal admission of criminal defamation.", 
         "Consult advocate; assert statutory exceptions (truth for public good or fair comment made in good faith)", "Criminal defamation trial and compensation damages lawsuits"),
        ("Citizen Rights", "Filing a Writ Petition (Article 102) for Enforcing Fundamental Constitutional Rights", 
         "Citizens endure years of bureaucratic abuse without knowing the High Court can quash illegal orders.", 
         "Engage Supreme Court advocate; prove violation of statutory law or fundamental constitutional right", "Permanent deprivation of civil liberty or property by arbitrary government order"),
        ("Citizen Rights", "Registering a Deed of Gift (দানপত্র দলিল) to Non-Family Members", 
         "Unlike Heba between close relatives, gift to non-relatives incurs standard high stamp duty and registration tax.", 
         "Calculate full stamp duty (3%) and local taxes; execute formal registered deed of gift with acceptance", "Deed rejected or challenged as fraudulent transfer"),
        ("Citizen Rights", "Executing a Registered Will (অসিয়তনামা / উইল) and Probate in Court", 
         "Under Muslim law, a person cannot bequeath more than 1/3rd of estate to non-heirs without heirs' consent.", 
         "Comply with 1/3rd testamentary limit; obtain Probate or Letters of Administration from District Judge", "Will declared void and set aside by civil court"),
        ("Citizen Rights", "Handling Mobile Court (ভ্রাম্যমাণ আদালত) summary trial and right to defense", 
         "Executive Magistrates sometimes conduct summary trials without giving reasonable opportunity to plead.", 
         "Politely request charges in writing, present purchase invoices or trade licenses, appeal to Sessions Court", "Wrongful imprisonment or confiscation of goods without trial"),
        ("Citizen Rights", "Evicting an Illegal Street Hawker Blocking Commercial Building Entrance", 
         "Physically assaulting hawkers triggers criminal charges; eviction requires municipal coordination.", 
         "File joint petition with City Corporation Estate Department and local Thana for eviction drive", "Violent street fights or criminal counter-complaints"),
        ("Citizen Rights", "Recovering Goods Confiscated by Airport Customs: Adjudication Appeal", 
         "Passengers forfeit seized luxury goods because they miss the 30-day appeal window.", 
         "File formal appeal before Commissioner of Customs (Appeals); pay redemption fine if approved", "Permanent government auction and forfeiture of valuable personal items"),
        ("Citizen Rights", "Defending against a False Dowry Case (Nari O Shishu Nirjatan Daman Ain)", 
         "Disgruntled in-laws weaponize Section 11 of the Act with non-bailable arrest warrants.", 
         "Collect timestamped alibi proof, bank statements proving zero dowry transactions, seek anticipatory bail", "Immediate arrest and months of pretrial detention"),
        ("Citizen Rights", "Legal Procedure for Changing Name in National Gazette (বাংলাদেশ গেজেট)", 
         "Changing full legal name requires Executive Magistrate affidavit followed by official Gazette publication.", 
         "First-class Magistrate affidavit, newspaper publication in two dailies, submit to BG Press for Gazette", "Institutions refusing to recognize altered name on official records"),
        ("Citizen Rights", "Filing an Appeal before the Information Commission under RTI Act 2009", 
         "Government departments illegally withhold public information regarding budgets and tender allocations.", 
         "Submit Form KA to Designated Officer; if refused within 20 days, file appeal to Information Commission", "Government corruption and misuse of public funds remaining hidden"),
        ("Citizen Rights", "Handling Land Demarcation Dispute with Neighbor (Amin Survey Protocol)", 
         "Calling a private biased surveyor leads to violent physical fights over boundary lines.", 
         "Submit application to Assistant Commissioner (Land) for official government Kanungo survey", "Boundary wall demolition and violent neighborhood feuds"),
        ("Citizen Rights", "Filing an Eviction Suit against Defaulting Tenant under Premises Rent Control Act", 
         "Landlord accepting rent after sending eviction notice legally waives the notice under waiver doctrine.", 
         "Serve 15-day notice to quit under Section 106 TP Act; refuse subsequent rent; file suit before Rent Controller", "Lawsuit dismissed because landlord accepted rent during litigation")
    ]
    for sub, title, prob, check, risk in l_items:
        scenarios.append((cat_leg, sub, title, prob, prob, check, risk))

    return scenarios

print("Matrix expander ready.")
